import Mathlib

/-!
# Multiquadratic fields and genus theory: target signatures

The narrative roadmap (the layer-by-layer build plan Layers 0–3, the worked examples, and
the references) is in `README.md`. Mathlib has quadratic fields, Kummer theory, quadratic
reciprocity, and the class group, but nothing on multiquadratic extensions
`ℚ(√d₁, …, √dₙ)` or the genus theory they encode; we build that here in `TauCeti/`.

This file holds the **Layer 0** targets — the degree and Galois group of a multiquadratic
field under square-class independence — together with a non-vacuity worked example. They
elaborate against the pinned Mathlib and are stated with `sorry` (allowed in this
human-owned roadmap library). As later layers make their types expressible in `TauCeti/`,
add their milestones here with `sorry`: the prime-splitting law (Layer 1), the 2-torsion
`Cl/Cl²` (Layer 2), and the genus field with the 2-rank theorem (Layer 3).

The Layer-0 square-class machinery is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance); credit it in
the ported `TauCeti/` files.
-/

namespace TauCetiRoadmap.Multiquadratic

universe u v

/-- **Non-vacuity worked example.** The smallest nontrivial multiquadratic degree:
`[ℚ(√2, √3) : ℚ] = 4`. -/
example :
    Module.finrank ℚ
      (IntermediateField.adjoin ℚ {Real.sqrt 2, Real.sqrt 3} : IntermediateField ℚ ℝ) = 4 :=
  sorry

variable {K : Type u} {L : Type v} [Field K] [Field L] [Algebra K L]

/-- **Layer 0 — multiquadratic degree.** If no nonempty subset product of the radicands
`d i` is a square in `K` (square-class / `ZMod 2`-linear independence of their classes in
`Kˣ ⧸ (Kˣ)²`), then the field generated over `K` by their square roots `r i` has degree
`2 ^ |ι|`. The rational and prime-indexed versions are corollaries; the field-generic
statement is the theorem. -/
example {ι : Type*} [Fintype ι] [CharZero K] (d : ι → K) (r : ι → L)
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    Module.finrank K (IntermediateField.adjoin K (Set.range r)) = 2 ^ Fintype.card ι :=
  sorry

/-- **Layer 0 — the Galois group is elementary abelian of exponent 2.** Under the same
square-class independence, `K(√d₁, …, √dₙ)/K` is Galois with group `(ℤ/2)ⁿ`, generated by
the sign changes `√dⱼ ↦ ±√dⱼ`. (⚠ `IsGalois` and the exponent-2 facts are the easy half;
this explicit isomorphism is the harder, later target.) -/
example {ι : Type*} [Fintype ι] [CharZero K] (d : ι → K) (r : ι → L)
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    (↥(IntermediateField.adjoin K (Set.range r)) ≃ₐ[K]
        ↥(IntermediateField.adjoin K (Set.range r))) ≃* Multiplicative (ι → ZMod 2) :=
  sorry

end TauCetiRoadmap.Multiquadratic
