import Mathlib

/-!
# Totally ramified extensions of a local field: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is
`README.md`. The statements here suggest Lean forms for particular milestones, so that
contributors and reviewers converge on names and signatures; discharging all of them
finishes neither a layer nor the roadmap.

The narrative roadmap (the standing conventions, the consumed contract, the layer-by-layer build
plan Layers 0–4, the worked examples, and the references) is in `README.md`. Mathlib has the local
field itself — `IsNonarchimedeanLocalField` (`Mathlib/NumberTheory/LocalField/Basic.lean`), with
`𝒪[K]` a complete discrete valuation ring, `𝓀[K]` finite, and `IsAdicComplete 𝓂[K] 𝒪[K]` all
available by `inferInstance` — together with Eisenstein polynomials, `Algebra.discr`,
`differentIdeal`, `Ideal.ramificationIdx'`, `HenselianLocalRing`, and Haar measure on a locally
compact group. It has **no** quantitative Newton estimate (only qualitative Hensel), **no**
non-archimedean analogue of `Measure.addHaar_image_linearMap`, and — the ultimate target — **no**
mass formula counting the totally ramified extensions of given degree ([Serre 1978]).

⚠ **The ramification-theoretic substrate is consumed, not built here.** Total ramification,
Eisenstein generators, monogenicity, the different and the discriminant, the exponent `d`, and
the tame criterion are targets of the *local fields and ramification* roadmap
(`../LocalFieldsRamification/README.md`). The `def`s below marked *consumed* record the shape this
roadmap needs them in, so that its own statements are expressible before that roadmap lands; when
it lands they are deleted here and its definitions are used instead. Do not treat them as targets.

This file pins the roadmap's load-bearing **definitions** (`residueCard`,
`totallyRamifiedOfDegree`, `wildExponent`, `IsRepresentativeSet`, and the coefficient-space
objects `toPoly`, `eisensteinSet`, `integerBox`) and its **named milestones** as `sorry`-targets
(`sorry` is allowed in this human-owned roadmap library — these are goals, not proofs).

⚠ The definitions are **junk-tolerant on purpose**: for `L` infinite over `K`, or for `n = 0`,
they take junk values. That is why every milestone carries `0 < n` and membership in
`totallyRamifiedOfDegree K n`. Do not repair the junk by adding finiteness hypotheses to the
definitions.

Two layers are stated over an arbitrary complete discrete valuation ring rather than over a local
field, because that is the generality their proofs have: `exists_isRoot` and `card_aroots_eq`
(Layer 1, `TauCeti/RingTheory/DiscreteValuationRing/`) and `card_quotient_range` (Layer 2,
`TauCeti/MeasureTheory/Group/`). Everything else belongs in
`TauCeti/NumberTheory/LocalField/MassFormula/`.
-/

open ValuativeRel
open scoped ENNReal

namespace TauCetiRoadmap.TotallyRamified

variable (K : Type*) [Field K] [ValuativeRel K] [UniformSpace K] [IsUniformAddGroup K]
  [IsNonarchimedeanLocalField K]

/-! ## Layer 0: the counting invariants

`maximalIdealAbove`, `ramificationIdx`, `IsTotallyRamified`, `discriminantIdeal` and
`discExponent` are *consumed* shapes (see the header): the local fields and ramification roadmap
owns total ramification, the discriminant, and its exponent. `residueCard`,
`totallyRamifiedOfDegree`, `wildExponent` and `IsRepresentativeSet` are this roadmap's own. -/

/-- The residue cardinality of a non-archimedean local field — Serre's `q`. -/
noncomputable def residueCard : ℕ :=
  Nat.card 𝓀[K]

variable {K}

/-- The maximal ideal of the ring of integers of a subextension `L` of `SeparableClosure K` / `K`,
described instance-freely as the radical of `𝓂[K]` extended along the structure map. For `L / K`
finite this is the maximal ideal of the local ring `integralClosure ↥𝒪[K] ↥L`; the definition
itself carries no such obligation, and is junk for `L` infinite over `K`. -/
noncomputable def maximalIdealAbove (L : IntermediateField K (SeparableClosure K)) :
    Ideal ↥(integralClosure ↥𝒪[K] ↥L) :=
  (Ideal.map (algebraMap ↥𝒪[K] ↥(integralClosure ↥𝒪[K] ↥L)) 𝓂[K]).radical

/-- The ramification index of a subextension `L` / `K`, through Mathlib's junk-tolerant
`Ideal.ramificationIdx'`. -/
noncomputable def ramificationIdx (L : IntermediateField K (SeparableClosure K)) : ℕ :=
  Ideal.ramificationIdx' 𝓂[K] (maximalIdealAbove L)

/-- `L / K` is *totally ramified* when its ramification index equals its degree. -/
def IsTotallyRamified (L : IntermediateField K (SeparableClosure K)) : Prop :=
  ramificationIdx L = Module.finrank K ↥L

variable (K)

/-- Serre's `σ_K(n)`: the subextensions of `SeparableClosure K` that are totally ramified of
degree `n` over `K`. -/
def totallyRamifiedOfDegree (n : ℕ) : Set (IntermediateField K (SeparableClosure K)) :=
  {L | Module.finrank K ↥L = n ∧ IsTotallyRamified L}

variable {K}

/-- The discriminant ideal of a subextension: the ideal of `𝒪[K]` generated by the elements whose
image in `K` is `Algebra.discr K b` for a `K`-basis `b` of `L` with integral entries. In the finite
separable case this is the classical discriminant ideal; the span form needs neither freeness nor
Dedekind-domain instances, and is `⊥` — junk — for `L` infinite over `K`. -/
noncomputable def discriminantIdeal (L : IntermediateField K (SeparableClosure K)) :
    Ideal ↥𝒪[K] :=
  Ideal.span {x : ↥𝒪[K] | ∃ b : Module.Basis (Fin (Module.finrank K ↥L)) K ↥L,
    (∀ i, IsIntegral 𝒪[K] (b i)) ∧ algebraMap 𝒪[K] K x = Algebra.discr K ⇑b}

/-- The discriminant exponent `d L`: the multiplicity of `𝓂[K]` in `discriminantIdeal L`. -/
noncomputable def discExponent (L : IntermediateField K (SeparableClosure K)) : ℕ :=
  multiplicity 𝓂[K] (discriminantIdeal L)

/-- The wild exponent `c L = d L − n + 1`, in the truncation-safe form `d L + 1 − n`. The bound
`n − 1 ≤ d L` that makes the truncated subtraction faithful is `sub_one_le_discExponent`. -/
noncomputable def wildExponent (L : IntermediateField K (SeparableClosure K)) : ℕ :=
  discExponent L + 1 - Module.finrank K ↥L

/-- Serre's "set of representatives of the isomorphism classes", as a predicate rather than a
quotient: `R` consists of members of `totallyRamifiedOfDegree K n`, and every member is
`K`-isomorphic to exactly one element of `R`. -/
def IsRepresentativeSet (n : ℕ) (R : Set (IntermediateField K (SeparableClosure K))) : Prop :=
  R ⊆ totallyRamifiedOfDegree K n ∧
    ∀ L ∈ totallyRamifiedOfDegree K n, ∃! M, M ∈ R ∧ Nonempty (↥L ≃ₐ[K] ↥M)

/- Eisenstein monogenicity ([Serre 1979, Chap. I, §6, Prop. 17]) and the statement that an
Eisenstein root generates a totally ramified extension are milestones of the *local fields and
ramification* roadmap, not of this one, and are deliberately not restated here. -/

/-- The **bridge**, and the target that turns a statement about `totallyRamifiedOfDegree K n` into
a computation: the consumed equivalence "totally ramified ⟺ Eisenstein", transported into
`IntermediateField K (SeparableClosure K)` and packaged with the degree, which is the form every
later layer applies. -/
theorem exists_eisenstein_generator (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ totallyRamifiedOfDegree K n) :
    ∃ (x : SeparableClosure K) (π : ↥𝒪[K]), Irreducible π ∧ IsIntegral 𝒪[K] x ∧
      (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}) ∧
      IntermediateField.adjoin K {x} = L ∧ (minpoly 𝒪[K] x).natDegree = n :=
  sorry

variable (K)

/-- `c L` is a nonnegative integer ([Serre 1978, p.1031, footnote 1]): in the `ℕ`-model, the bound
`n − 1 ≤ d L`, which is what makes the truncated subtraction defining `wildExponent` faithful.
This is a **corollary of the consumed contract** — the tame equality `d = e − 1` together with the
wild lower bound `e ≤ d` — restated here in the form the count applies, not a fresh development. -/
theorem sub_one_le_discExponent (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ totallyRamifiedOfDegree K n) :
    n - 1 ≤ discExponent L :=
  sorry

/-- **The tame criterion, as the count uses it** ([Serre 1978, p.1031]): `c L = 0` exactly when `n`
is prime to the residue characteristic. Again a corollary of the consumed `d = e − 1 ⟺ tame`,
rephrased in terms of `c`; the ramification-theoretic content belongs to that roadmap. -/
theorem wildExponent_eq_zero_iff (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ totallyRamifiedOfDegree K n) :
    wildExponent L = 0 ↔ ¬ ringChar 𝓀[K] ∣ n :=
  sorry

variable {K}

/-- `d`, hence `c`, is an invariant of the `K`-isomorphism class — the fact along which Theorem 1
is regrouped into Theorem 2. -/
theorem discExponent_eq_of_algEquiv {L M : IntermediateField K (SeparableClosure K)}
    (e : ↥L ≃ₐ[K] ↥M) : discExponent L = discExponent M :=
  sorry

/- **The comparison with the different** ([Serre 1979, Chap. III, §3]) — the discriminant ideal is
the relative norm of Mathlib's `differentIdeal` — belongs to the *local fields and ramification*
roadmap, which owns the different and the discriminant alike, and is not a target here. -/

/-! ## Layer 1: quantitative Newton lifting over a complete discrete valuation ring

Stated for an arbitrary complete discrete valuation ring; the local-field case is an instance.
This strictly refines Mathlib's `HenselianLocalRing`, which lifts a simple root modulo the maximal
ideal and gives no distance bound. -/

/-- **Newton iteration with an estimate.** If the order of `F` at `y₀` exceeds twice that of its
derivative, the iteration converges to a root `z` whose distance to `y₀` has order at least the
difference. Uniqueness of the root in that ball is a companion target. -/
theorem exists_isRoot {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [IsAdicComplete (IsLocalRing.maximalIdeal A) A] (F : Polynomial A) (y₀ : A)
    (hlt : IsDiscreteValuationRing.addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) +
        IsDiscreteValuationRing.addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) <
      IsDiscreteValuationRing.addVal A (Polynomial.eval y₀ F)) :
    ∃ z : A, F.IsRoot z ∧
      IsDiscreteValuationRing.addVal A (Polynomial.eval y₀ F) ≤
        IsDiscreteValuationRing.addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) +
          IsDiscreteValuationRing.addVal A (z - y₀) :=
  sorry

/-- **Local constancy of the root count**, the form Layer 3 consumes: for a monic `f` over `𝒪[K]`,
separable over `K`, coefficientwise closeness forces equality of root counts in every member of
`totallyRamifiedOfDegree K n`. -/
theorem card_aroots_eq (n : ℕ) (hn : 0 < n) (L : IntermediateField K (SeparableClosure K))
    (hL : L ∈ totallyRamifiedOfDegree K n) {f : Polynomial ↥𝒪[K]} (hfm : f.Monic)
    (hfsep : (f.map (algebraMap ↥𝒪[K] K)).Separable) :
    ∃ T : ℕ, 0 < T ∧ ∀ g : Polynomial ↥𝒪[K], g.Monic →
      (∀ i, g.coeff i - f.coeff i ∈ 𝓂[K] ^ T) →
      ((g.map (algebraMap ↥𝒪[K] K)).aroots ↥L).card =
        ((f.map (algebraMap ↥𝒪[K] K)).aroots ↥L).card :=
  sorry

/-! ## Layer 2: the lattice index and the Haar scaling law

Also stated over an arbitrary complete discrete valuation ring, with finite residue field. -/

/-- **The index of an image lattice.** For an integral matrix whose determinant is associated to
`π ^ k`, the integer box modulo its image has exactly `q ^ k` elements — Smith normal form over the
principal ideal ring `A`. This is the arithmetic half of the scaling law; the measure-theoretic
half (`μ (M · S) = q ^ (−k) · μ S` for the box and for balls, the non-archimedean analogue of
`Measure.addHaar_image_linearMap`) is the other Layer-2 target. -/
theorem card_quotient_range {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Finite (IsLocalRing.ResidueField A)] {n : ℕ} (M : Matrix (Fin n) (Fin n) A)
    (hdet : M.det ≠ 0) {π : A} (hπ : Irreducible π) {k : ℕ} (hk : Associated M.det (π ^ k)) :
    Nat.card ((Fin n → A) ⧸ LinearMap.range (Matrix.mulVecLin M)) =
      Nat.card (IsLocalRing.ResidueField A) ^ k :=
  sorry

/-! ## Layer 3: the coefficient space, the Eisenstein region, and its measure -/

variable (K)

/-- A monic polynomial of degree `n` *is* its coefficient vector, with `a i` the coefficient of
`X ^ i`. -/
noncomputable def toPoly {n : ℕ} (a : Fin n → K) : Polynomial K :=
  Polynomial.X ^ n + ∑ i : Fin n, Polynomial.C (a i) * Polynomial.X ^ (i : ℕ)

/-- The Eisenstein region ([Serre 1978, eq. (1)]): every coefficient in the open unit ball, with
the constant term of the largest valuation below `1` — that of a uniformizer. -/
def eisensteinSet (n : ℕ) : Set (Fin n → K) :=
  {a | (∀ i, valuation K (a i) < 1) ∧
    ∀ y : K, valuation K y < 1 → valuation K y ≤ valuation K ((toPoly K a).coeff 0)}

/-- The integer box of the coefficient space: the set on which the measure is normalized. It is
compact with nonempty interior, so `Measure.addHaarMeasure` on it is the paper's measure; the
statements below take the normalization as a hypothesis instead, which keeps them free of a
bespoke measure definition. -/
def integerBox (n : ℕ) : Set (Fin n → K) :=
  Set.univ.pi fun _ => (𝒪[K] : Set K)

/-- **The measure of the Eisenstein region** is `q ^ (−n) · (1 − q ^ (−1))` — the normalization
check that catches a misnormalized Haar measure long before the summit. -/
theorem measure_eisensteinSet (n : ℕ) (hn : 0 < n)
    [MeasurableSpace (Fin n → K)] [BorelSpace (Fin n → K)]
    (μ : MeasureTheory.Measure (Fin n → K)) [μ.IsAddHaarMeasure] (hμ : μ (integerBox K n) = 1) :
    μ (eisensteinSet K n) =
      (residueCard K : ℝ≥0∞)⁻¹ ^ n * (1 - (residueCard K : ℝ≥0∞)⁻¹) :=
  sorry

variable {K}

/-- The root count of Lemma 1: the number of roots of `toPoly a` lying in `L`, with multiplicity.
On the full-measure separable locus every multiplicity is `1`. -/
noncomputable def rootCount (L : IntermediateField K (SeparableClosure K)) {n : ℕ}
    (a : Fin n → K) : ℕ :=
  ((toPoly K a).aroots ↥L).card

variable (K)

/-- Almost everywhere on the Eisenstein region, the root counts over
`totallyRamifiedOfDegree K n` sum to `n`: an Eisenstein polynomial is irreducible, and each of its
`n` roots generates exactly one member. -/
theorem tsum_rootCount (n : ℕ) (hn : 0 < n)
    [MeasurableSpace (Fin n → K)] [BorelSpace (Fin n → K)]
    (μ : MeasureTheory.Measure (Fin n → K)) [μ.IsAddHaarMeasure] (hμ : μ (integerBox K n) = 1) :
    ∀ᵐ a ∂μ.restrict (eisensteinSet K n),
      ∑' L : totallyRamifiedOfDegree K n, (rootCount L.1 a : ℝ≥0∞) = n :=
  sorry

/-- **The integral of the root count** ([Serre 1978, Lemmas 2 and 3, eqs. (5)–(13)]): the change of
variables in power-basis coordinates, with Layer 2 supplying the factor `q ^ (−d L)`. Summing this
over `L` against `tsum_rootCount` is Theorem 1. -/
theorem lintegral_rootCount (n : ℕ) (hn : 0 < n)
    [MeasurableSpace (Fin n → K)] [BorelSpace (Fin n → K)]
    (μ : MeasureTheory.Measure (Fin n → K)) [μ.IsAddHaarMeasure] (hμ : μ (integerBox K n) = 1)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ totallyRamifiedOfDegree K n) :
    ∫⁻ a in eisensteinSet K n, (rootCount L a : ℝ≥0∞) ∂μ =
      (residueCard K : ℝ≥0∞)⁻¹ ^ (discExponent L + 1) * (1 - (residueCard K : ℝ≥0∞)⁻¹) :=
  sorry

/-! ## Layer 4: the mass formulas -/

/-- **Theorem 1, the first mass formula** ([Serre 1978, Thm. 1]). -/
theorem tsum_one_div_residueCard_pow_wildExponent (n : ℕ) (hn : 0 < n) :
    ∑' L : totallyRamifiedOfDegree K n, 1 / (residueCard K : ℝ≥0∞) ^ wildExponent L.1 = n :=
  sorry

/-- **The finiteness dichotomy** ([Serre 1978, Rmk. 1°]): infinite exactly in equal characteristic
`p` with `p ∣ n`. -/
theorem totallyRamifiedOfDegree_infinite_iff (n : ℕ) (hn : 0 < n) :
    (totallyRamifiedOfDegree K n).Infinite ↔ ringChar K = ringChar 𝓀[K] ∧ ringChar 𝓀[K] ∣ n :=
  sorry

/-- **Convergence** ([Serre 1978, Rmk. 1°]): the real-valued restatement, meaningful precisely in
the infinite case, where the `ℝ≥0∞` sum asserts nothing about summability. -/
theorem summable_one_div_residueCard_pow_wildExponent (n : ℕ) (hn : 0 < n) :
    Summable fun L : totallyRamifiedOfDegree K n => 1 / (residueCard K : ℝ) ^ wildExponent L.1 :=
  sorry

/-- **The orbit count** ([Serre 1978, Rmk. 3°]): the isomorphism class of `L` inside
`totallyRamifiedOfDegree K n` has `n / #Aut_K(L)` members, in multiplied form. -/
theorem ncard_isomorphic_mul_natCard_algEquiv (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ totallyRamifiedOfDegree K n) :
    {M ∈ totallyRamifiedOfDegree K n | Nonempty (↥L ≃ₐ[K] ↥M)}.ncard *
      Nat.card (↥L ≃ₐ[K] ↥L) = n :=
  sorry

/-- **Theorem 2, the mass formula proper** ([Serre 1978, Thm. 2]): Theorem 1 regrouped along
isomorphism classes, over any set of representatives. -/
theorem tsum_one_div_natCard_algEquiv_mul_residueCard_pow_wildExponent (n : ℕ) (hn : 0 < n)
    (R : Set (IntermediateField K (SeparableClosure K))) (hR : IsRepresentativeSet n R) :
    ∑' M : R, 1 / ((Nat.card (↥M.1 ≃ₐ[K] ↥M.1) : ℝ≥0∞) *
      (residueCard K : ℝ≥0∞) ^ wildExponent M.1) = 1 :=
  sorry

/-- **The tame count**, the corollary that makes the formula concrete: away from the residue
characteristic every `c L` vanishes, so there are exactly `n` totally ramified extensions of
degree `n`. -/
theorem ncard_totallyRamifiedOfDegree_of_not_dvd (n : ℕ) (hn : 0 < n)
    (hp : ¬ ringChar 𝓀[K] ∣ n) : (totallyRamifiedOfDegree K n).ncard = n :=
  sorry

end TauCetiRoadmap.TotallyRamified
