import Mathlib
import TauCeti.AlgebraicTopology.SimplicialComplex.Realization
import TauCeti.Combinatorics.PermutationTriple.Basic
import TauCeti.Combinatorics.RibbonGraph.Basic
import TauCeti.Topology.JordanCurve.Basic
import TauCeti.Topology.Triangulable

/-!
# Surface topology, finite presentations, and classification: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is
`README.md`. The declarations here suggest Lean forms for load-bearing objects and
particular milestones, so that contributors and reviewers converge on names and
signatures; discharging all of them finishes neither a layer nor the roadmap. `sorry` is
allowed in this human-owned roadmap library: these are targets, not completed proofs.

This roadmap chooses two-dimensional generalized maps as the finite hub. Oriented maps,
hypermaps, and polygonal schemas are presentations of the same finite surface data;
realization, Euler characteristic, orientability, and the main operations are defined at the
hub and compared to the other presentations. Layers 1 through 8 end in the classification of
compact surfaces; layers 9 and 10 build mapping class groups and planarity on top of it.

The file therefore pins more object-level vocabulary than many roadmaps do. Where the README
shapes a definition after an open Mathlib pull request, as for connectivity, degree, minors,
and drawings of Mathlib's `Graph α β`, this file compiles the shape that needs no new Mathlib
vocabulary and records the rest as comments, rather than introducing a private synonym to make
the targets parse. A condition that cannot yet be stated honestly is omitted rather than
replaced by `Prop := sorry`.
-/

noncomputable section

namespace TauCetiRoadmap.SurfaceTopology

open Function Set

universe u v w

/-! ## Layer 0: finite conventions -/

/-- A finite cyclic word with repeated labels, modulo cyclic rotation. The implementation
should remain separate from `CircularOrder` and from the topological circle. -/
def CyclicWord (α : Type u) : Type u :=
  sorry

/-- A bundled finite indexing type. Moves which add or remove cells must not pretend to
live on a fixed ambient type. -/
structure BundledFinite where
  ι : Type u
  fintype : Fintype ι
  decEq : DecidableEq ι

/-!
The isomorphism closure used by move relations should be compiled once the concrete
bundled object is known. The important constraint is that `Relation.ReflTransGen` is
applied *after* closing the elementary relation under isomorphism of the bundled index
type; Pachner/schema moves change that type.
-/

/-! ## Layer 1: generalized maps -/

/-- An `n`-dimensional generalized map: `n+1` involutions, with non-neighbouring
involutions commuting. This definition is dimension-polymorphic even though the roadmap
only develops the two-dimensional theory. -/
structure GMap (n : ℕ) (D : Type u) [Fintype D] [DecidableEq D] where
  adj : Fin (n + 1) → Equiv.Perm D
  involutive : ∀ i, Function.Involutive (adj i)
  commute_of_far : ∀ i j, i.1 + 2 ≤ j.1 → Function.Commute (adj i) (adj j)

abbrev GMap2 (D : Type u) [Fintype D] [DecidableEq D] := GMap 2 D

/-- The `i`-cells are the orbits of the group generated by all adjacencies except `αᵢ`. -/
def GMap.Cell {n : ℕ} {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap n D) (i : Fin (n + 1)) : Type u :=
  MulAction.orbitRel.Quotient (Subgroup.closure {σ | ∃ j, j ≠ i ∧ σ = G.adj j}) D

/-- Cells of a finite generalized map are finite orbit quotients. -/
instance GMap.instFiniteCell {n : ℕ} {D : Type u}
    [Fintype D] [DecidableEq D] (G : GMap n D) (i : Fin (n + 1)) :
    Finite (G.Cell i) :=
  inferInstanceAs (Finite (Quotient _))

/-- The connected components: the orbits of the group generated by all the adjacencies. -/
def GMap.Components {n : ℕ} {D : Type u} [Fintype D] [DecidableEq D] (G : GMap n D) : Type u :=
  MulAction.orbitRel.Quotient (Subgroup.closure (Set.range G.adj)) D

/-- Isomorphism of two-dimensional generalized maps, allowing the dart type to change. -/
structure GMap2.Iso {D : Type u} {D' : Type v}
    [Fintype D] [DecidableEq D] [Fintype D'] [DecidableEq D']
    (G : GMap2 D) (G' : GMap2 D') where
  toEquiv : D ≃ D'
  map_adj : ∀ i d, toEquiv (G.adj i d) = G'.adj i (toEquiv d)

/-- Euler characteristic as the cell count. Under the surface condition below this is the
Euler characteristic of the realization; Damiand–Lienhardt's Definition 91, the alternating
sum over all orbit types, is the Euler characteristic of the flag triangulation and is always
correct, but it is the cell count that every later layer wants. -/
def GMap2.eulerChar {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : ℤ :=
  (Nat.card (G.Cell 0) : ℤ) - Nat.card (G.Cell 1) + Nat.card (G.Cell 2)

/-- A boundary dart is a fixed point of the highest-order involution. -/
def GMap2.IsBoundaryDart {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) (d : D) : Prop :=
  G.adj 2 d = d

instance {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    DecidablePred G.IsBoundaryDart :=
  fun d => inferInstanceAs (Decidable (G.adj 2 d = d))

/-- The surface condition. No dart is fixed by `α₀` or `α₁`, so the boundary is recorded by
`α₂` alone, and no edge is folded onto itself, `α₂ d ≠ α₀ d`, so every orbit cell is a cell of
the realization. These are Damiand–Lienhardt's "no 0- or 1-boundary" and "no folded cell"
(§4.3.4.2, pp. 106–107; §8.3.2.1, p. 331). Every generalized map realizes to a surface without
any hypothesis (§2.4); the condition is the price of `eulerChar` being the Euler characteristic. -/
def IsSurfaceGMap {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : Prop :=
  (∀ d, G.adj 0 d ≠ d) ∧ (∀ d, G.adj 1 d ≠ d) ∧ (∀ d, G.adj 2 d ≠ G.adj 0 d)

instance {D : Type u} [Fintype D] [DecidableEq D] : DecidablePred (IsSurfaceGMap (D := D)) :=
  fun G => by unfold IsSurfaceGMap; infer_instance

/-- A closed surface map: no boundary darts either. -/
def IsClosedSurfaceGMap {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : Prop :=
  IsSurfaceGMap G ∧ ∀ d, G.adj 2 d ≠ d

instance {D : Type u} [Fintype D] [DecidableEq D] :
    DecidablePred (IsClosedSurfaceGMap (D := D)) :=
  fun G => by unfold IsClosedSurfaceGMap; infer_instance

/-- The map on two darts with all three involutions the swap: one edge folded onto itself by a
half-turn about its midpoint. Its realization is a sphere, since the flag triangulation has
three vertices, three edges, and two triangles, but the cell count is `1 - 1 + 1 = 1`. This
is the folded cell the third condition excludes. -/
def allSwap : GMap2 Bool where
  adj _ := Equiv.swap true false
  involutive _ := Equiv.swap_apply_self true false
  commute_of_far _ _ _ := Function.Commute.refl _

example : ¬ IsSurfaceGMap allSwap := fun h => h.2.2 true rfl

/-- The projective plane as the one-face schema `a a`: four darts, `α₀ = (0 1)(2 3)`,
`α₁ = (1 2)(3 0)`, `α₂ = (0 2)(1 3)`. One vertex, one edge, one face, and the surface condition
holds, so this one-cell presentation is admitted, as it must be. -/
def projectivePlane : GMap2 (Fin 4) where
  adj := ![Equiv.swap 0 1 * Equiv.swap 2 3, Equiv.swap 1 2 * Equiv.swap 3 0,
    Equiv.swap 0 2 * Equiv.swap 1 3]
  involutive := by
    intro i
    fin_cases i <;> (intro x; fin_cases x <;> decide)
  commute_of_far := by
    intro i j hij x
    fin_cases i <;> fin_cases j <;> fin_cases x <;> decide

example : IsSurfaceGMap projectivePlane := by decide

example : IsClosedSurfaceGMap projectivePlane := by decide

/-- Orientability as bipartiteness of the dart-adjacency graph, ignoring fixed
adjacencies representing boundary. -/
def GMap2.IsOrientable {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : Prop :=
  ∃ S : Set D, ∀ i d, G.adj i d ≠ d → (d ∈ S ↔ G.adj i d ∉ S)

/-- A chosen orientation is extra data; `IsOrientable` is only the existence property. -/
structure GMap2.Orientation {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) where
  side : Set D
  flips : ∀ i d, G.adj i d ≠ d → (d ∈ side ↔ G.adj i d ∉ side)

/-- Orientations of cells are intrinsic: an edge is oriented by choosing one of its two ends,
the two `⟨α₂⟩`-orbits inside its dart orbit. -/
def GMap2.EdgeOrientation {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D)
    (e : G.Cell 1) : Type u :=
  sorry

/-- A face is oriented by choosing one of the two ways round it, the two `⟨α₀ α₁⟩`-orbits
inside its dart orbit. -/
def GMap2.FaceOrientation {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D)
    (f : G.Cell 2) : Type u :=
  sorry

/-- The boundary 1-map: the boundary darts, with `α₀` and the involution that walks around a
boundary vertex to the next boundary dart. Its components are the boundary circles. -/
noncomputable def GMap2.boundary {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    GMap 1 {d // G.IsBoundaryDart d} :=
  sorry

/-- The number of boundary circles. -/
noncomputable def GMap2.boundaryComponentCount {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : ℕ :=
  Nat.card G.boundary.Components

/-- A generalized map with its finite dart type bundled. This is the codomain of moves
which change the number or type of darts. -/
structure BundledGMap2 where
  D : Type u
  fintypeD : Fintype D
  decEqD : DecidableEq D
  map : @GMap 2 D fintypeD decEqD

/-!
Still to pin here: connectedness (`Nat.card G.Components = 1`), the orientation of the
boundary circles induced by a `GMap2.Orientation` (the surface on the left, as `PlanarTopology`
layer 6 fixes it), and the two genus formulas

  def GMap2.orientableGenus (G) (h : G.IsConnected ∧ IsSurfaceGMap G ∧ G.IsOrientable) : ℕ
  def GMap2.nonorientableGenus (G) (h : G.IsConnected ∧ IsSurfaceGMap G ∧ ¬ G.IsOrientable) : ℕ

whose identification with the genera of the standard surfaces is layer 8's. Beside the two
examples above, the implementation should carry a map with an `α₀`-fixed dart and one with an
`α₁`-fixed dart as negative tests, a dangling edge (`α₂ d = α₁ d`) as a positive test of
multiple incidence, and the sphere, torus, Klein bottle, disc, annulus, and Möbius band as
decidable tests of the definition.
-/

/-! ## Layer 2: presentations and comparison theorems -/

/-- An oriented combinatorial map / rotation system. -/
structure CombinatorialMap (D : Type u) [Fintype D] [DecidableEq D] where
  sigma : Equiv.Perm D
  alpha : Equiv.Perm D
  alpha_involutive : Function.Involutive alpha
  alpha_free : ∀ d, alpha d ≠ d

/-- Passing from an oriented map to the unoriented generalized-map hub doubles darts. -/
noncomputable def CombinatorialMap.toGMap2 {D : Type u} [Fintype D] [DecidableEq D]
    (M : CombinatorialMap D) : GMap2 (D × Bool) :=
  sorry

/-- A hypermap in the three-permutation presentation. -/
structure Hypermap (D : Type u) [Fintype D] [DecidableEq D] where
  sigma : Equiv.Perm D
  phi : Equiv.Perm D
  alpha : Equiv.Perm D
  comp : sigma * phi * alpha = 1

/-- Conversion from a hypermap to the generalized-map hub. -/
noncomputable def Hypermap.toGMap2 {D : Type u} [Fintype D] [DecidableEq D]
    (H : Hypermap D) : GMap2 (D × Bool) :=
  sorry

/-- BelyiMaps' finite objects are the orientable boundaryless case: a permutation triple is a
hypermap on `Fin n` in the convention `σinf * σ1 * σ0 = 1`. -/
noncomputable def Hypermap.toPermutationTriple {D : Type u} [Fintype D] [DecidableEq D] {n : ℕ}
    (H : Hypermap D) (e : D ≃ Fin n) : TauCeti.PermutationTriple n :=
  sorry

/-- The converse conversion. -/
noncomputable def PermutationTriple.toHypermap {n : ℕ} (t : TauCeti.PermutationTriple n) :
    Hypermap (Fin n) :=
  sorry

/-- A bipartite ribbon graph is an oriented map whose white vertices all have degree two: the
edges of the ribbon graph are the darts, the black rotation is `σ`, and the white rotation is
the edge involution. -/
noncomputable def CombinatorialMap.toBipartiteRibbonGraph {D : Type u} [Fintype D]
    [DecidableEq D] (M : CombinatorialMap D) : TauCeti.BipartiteRibbonGraph.{u} :=
  sorry

/-- The converse, under the degree-two hypothesis. -/
noncomputable def BipartiteRibbonGraph.toCombinatorialMap (Γ : TauCeti.BipartiteRibbonGraph.{u})
    (h : ∀ w, Γ.whiteDegree w = 2) : CombinatorialMap Γ.E :=
  sorry

/-- The Euler characteristics agree along the conversion. -/
example (Γ : TauCeti.BipartiteRibbonGraph.{u}) (h : ∀ w, Γ.whiteDegree w = 2) :
    (BipartiteRibbonGraph.toCombinatorialMap Γ h).toGMap2.eulerChar = Γ.eulerChar := by
  sorry

/-- Polygonal schemas are bundled because relabelling and cancellation change the label
type. A label occurring twice is glued and a label occurring once is a boundary edge; the
remaining surface validity is a separate predicate, not hidden in an unconstrained field. -/
structure PolygonalSchema where
  label : Type u
  fintypeLabel : Fintype label
  decEqLabel : DecidableEq label
  faces : List (CyclicWord (label × Bool))

/-- The generalized map of a schema: two darts per side, `α₀` along a side, `α₁` around a
corner of the face, `α₂` the gluing of the two occurrences of a label, and `α₂`-fixed darts on
the sides whose label occurs once. -/
noncomputable def PolygonalSchema.toGMap2 (S : PolygonalSchema.{u}) : BundledGMap2.{u} :=
  sorry

/-- The schema of a surface map, given an orientation of each edge: the labels are the edges,
each face contributes its traversal word, with a sign recording whether the traversal agrees
with the edge's orientation, and boundary edges occur once. -/
noncomputable def GMap2.toSchema {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D)
    (h : IsSurfaceGMap G) (o : ∀ e : G.Cell 1, G.EdgeOrientation e) : PolygonalSchema.{u} :=
  sorry

/-!
The comparison theorems are central targets; most wait on the realization and subdivision
APIs. Representative forms:

  -- 1. The flag complex of `K.toGMap2` is the barycentric subdivision of `K`; no subdivision
  --    of `K` is needed, since a flag of a simplicial complex is determined by its cells.
  theorem flagComplex_toGMap2 (hK : IsCombinatorialSurface K) :
      K.toGMap2.flagComplex ≅ K.barycentricSubdivision
  -- 2. The realization of a generalized map is the realization of the flag complex of its
  --    barycentric subdivision (layer 3).
  theorem realization_homeomorph_flagComplex ...
  -- 3. Oriented maps round-trip through the hub, with a chosen orientation.
  theorem toGMap2_toCombinatorialMap ...
  -- 4. Duality is an involution.
  theorem dual_dual ...
  -- 5. Schemas and surface maps round-trip up to relabelling.
  theorem toSchema_toGMap2 ... and theorem toGMap2_toSchema ...
  -- 6. The BelyiMaps comparisons preserve Euler characteristic and connectedness; the
  --    permutation-triple Euler characteristic is on Tau Ceti main
  --    (`Combinatorics/PermutationTriple/EulerCharacteristic.lean`).
  theorem PermutationTriple.eulerChar_toHypermap (t) : t.toHypermap.toGMap2.eulerChar = t.eulerChar

The implementation should exhibit two non-isomorphic surface maps with the same incidence
poset of cells (Damiand–Lienhardt, Fig. 2.29): the poset forgets which of a face's several
incidences to an edge is which, which is why the hub is darts and not a poset.
-/

/-! ## Layer 3: realization -/

/-- Direct topological realization of a generalized map as triangles modulo side gluings.
It is defined for every generalized map, before any surface condition, and not through an
abstract simplicial complex. -/
noncomputable def GMap2.realization {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : Type u :=
  sorry

/-- The quotient realization carries its quotient topology. -/
noncomputable instance GMap2.realizationTopologicalSpace
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    TopologicalSpace G.realization :=
  sorry

/-- The direct realization of a finite generalized map is compact. -/
instance GMap2.realizationCompactSpace
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    CompactSpace G.realization :=
  sorry

/-- And Hausdorff. -/
instance GMap2.realizationT2Space
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    T2Space G.realization :=
  sorry

/-- Every 2-generalized map realizes to a surface with boundary: the structure itself, in
`PlanarTopology`'s half-space family, not an existence statement. -/
@[instance_reducible] noncomputable def GMap2.realizationChartedSpace
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) :
    ChartedSpace (EuclideanHalfSpace 2) G.realization :=
  sorry

/-- The realization of a bundled map, with its topology. -/
noncomputable def BundledGMap2.realization (B : BundledGMap2.{u}) : Type u :=
  @GMap2.realization B.D B.fintypeD B.decEqD B.map

noncomputable instance (B : BundledGMap2.{u}) : TopologicalSpace B.realization :=
  @GMap2.realizationTopologicalSpace B.D B.fintypeD B.decEqD B.map

/-- Every compact surface arises, by Radó. -/
example (M : Type*) [TopologicalSpace M] [ChartedSpace (EuclideanHalfSpace 2) M] [T2Space M]
    [CompactSpace M] :
    ∃ (D : Type) (_ : Fintype D) (_ : DecidableEq D) (G : GMap2 D),
      IsSurfaceGMap G ∧ Nonempty (G.realization ≃ₜ M) := by
  sorry

/-!
Once `PlanarTopology`'s `Surface.eulerChar`, `Surface.IsOrientable`, `Surface.Orientation`,
and `boundaryComponentCount` exist, add the decisive milestones:

  -- Under the first two surface conditions the boundary is the image of the `α₂`-fixed
  -- sides, one circle per component of the boundary 1-map.
  theorem GMap2.boundary_realization (h₀ : ∀ d, G.adj 0 d ≠ d) (h₁ : ∀ d, G.adj 1 d ≠ d) : ...
  theorem GMap2.boundaryComponentCount_realization (h₀) (h₁) :
      boundaryComponentCount G.realization = G.boundaryComponentCount

  -- Under the full surface condition the orbit cells are the cells of the realization.
  theorem IsSurfaceGMap.eulerChar_eq (h : IsSurfaceGMap G) :
      Surface.eulerChar G.realization = G.eulerChar
  theorem IsSurfaceGMap.isOrientable_iff (h : IsSurfaceGMap G) :
      Surface.IsOrientable G.realization ↔ G.IsOrientable
  theorem IsSurfaceGMap.orientationEquiv (h : IsSurfaceGMap G) (hc : G.IsConnected) :
      Surface.Orientation G.realization ≃ G.Orientation

  -- The simplicial bridge is a theorem about one barycentric subdivision, not a definition:
  -- after one subdivision every flag triple is injective, because each triple contains the
  -- original dart as its face-vertex.
  theorem GMap2.flagComplex_isSimplicial_of_subdivided (G) :
      Function.Injective G.barycentricSubdivision.flagTriple
  theorem GMap2.realization_homeomorph_flagComplex (G) :
      G.realization ≃ₜ Realization G.barycentricSubdivision.flagComplex

The projective-plane map `projectivePlane` above must remain an explicit counter-witness to
defining realization through the unsubdivided flag complex.
-/

/-! ## Layer 4: operations on finite surfaces -/

/-- Edge subdivision changes the dart type, hence returns a bundled map. -/
noncomputable def GMap2.subdivideEdge {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) (e : G.Cell 1) : BundledGMap2 :=
  sorry

/-- Face subdivision likewise changes the dart type. -/
noncomputable def GMap2.subdivideFace {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) (f : G.Cell 2) : BundledGMap2 :=
  sorry

/-- Duality reverses the three adjacencies. It is defined for every map; that it preserves the
closed-surface condition and the realization is asserted only for closed surface maps
(`dual_isClosedSurface`, `dual_realization`). -/
noncomputable def GMap2.dual {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : GMap2 D :=
  sorry

/-- The orientation double cover has two sheets indexed by `Bool`. -/
noncomputable def GMap2.orientationDoubleCover
    {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) : GMap2 (D × Bool) :=
  sorry

/-- Capping glues a disc on each boundary circle and may change the dart type. It is one of
the controlled operations, with its Euler-characteristic formula; it is not on the
classification path. -/
noncomputable def GMap2.cap {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : BundledGMap2 :=
  sorry

/-- Doubling along the boundary uses two copies of the dart set. -/
noncomputable def GMap2.double {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : GMap2 (D × Bool) :=
  sorry

/-- Connected sum is another index-changing operation. -/
noncomputable def GMap2.connectedSum
    {D : Type u} {E : Type v}
    [Fintype D] [DecidableEq D] [Fintype E] [DecidableEq E]
    (G : GMap2 D) (H : GMap2 E) : BundledGMap2 :=
  sorry

/-!
Admissible edge contraction, the edge flip (the `2 ↔ 2` move), and cutting along a
combinatorial curve should be compiled only after `IsContractible` and `CombinatorialCurve`
are real predicates/types. Their realization theorems, not merely orbit-count identities, are
the milestones:

  theorem GMap2.subdivideEdge_realization : (G.subdivideEdge e).realization ≃ₜ G.realization
  theorem GMap2.dual_isClosedSurface (h : IsClosedSurfaceGMap G) : IsClosedSurfaceGMap G.dual
  theorem GMap2.dual_realization (h : IsClosedSurfaceGMap G) : G.dual.realization ≃ₜ G.realization
  theorem GMap2.orientationDoubleCover_isCovering : IsCoveringMap G.orientationDoubleCover.projection
  theorem GMap2.cap_eulerChar : G.cap.eulerChar = G.eulerChar + G.boundaryComponentCount
  theorem GMap2.double_eulerChar : G.double.eulerChar = 2 * G.eulerChar
-/

/-! ## Layer 5: embedded graphs and the Heffter--Edmonds--Ringel correspondence -/

/-- The range of a path that is injective except that the two endpoints of a loop coincide:
the shape of Mathlib's draft `IsPrimitiveLink` (mathlib4 #43687). -/
def IsPrimitiveLink {M : Type*} [TopologicalSpace M] (A : Set M) (x y : M) : Prop :=
  ∃ γ : Path x y, Set.range γ = A ∧
    ∀ s t, γ s = γ t → s = t ∨ ({s, t} : Set unitInterval) = {0, 1}

/-- A drawing of a multigraph in a space, in the shape of Mathlib's draft `Drawing`: an
injective placement of the vertices and, for each edge, an arc between the placements of its
ends, with vertices lying only on their own edges. -/
structure Drawing {α β : Type*} (Γ : Graph α β) (M : Type*) [TopologicalSpace M] where
  vertex : Γ.vertexSet ↪ M
  edgeRange : Γ.edgeSet → Set M
  edge_isPrimitiveLink : ∀ (e : Γ.edgeSet) (u v : Γ.vertexSet), Γ.IsLink e.1 u.1 v.1 →
    IsPrimitiveLink (edgeRange e) (vertex u) (vertex v)
  inc_of_vertex_mem : ∀ (e : Γ.edgeSet) (v : Γ.vertexSet), vertex v ∈ edgeRange e → Γ.Inc e.1 v.1

namespace Drawing

variable {α β : Type*} {Γ : Graph α β} {M : Type*} [TopologicalSpace M]

/-- Noncrossing: distinct edge interiors are disjoint. -/
def IsNoncrossing (D : Drawing Γ M) : Prop :=
  Pairwise fun e e' =>
    Disjoint (D.edgeRange e \ Set.range D.vertex) (D.edgeRange e' \ Set.range D.vertex)

/-- The support: the vertex placements and the edge arcs. -/
def support (D : Drawing Γ M) : Set M :=
  Set.range D.vertex ∪ ⋃ e, D.edgeRange e

/-- Cellular: every component of the complement of the support is an open disc. -/
def IsCellular (D : Drawing Γ M) : Prop :=
  ∀ x ∉ D.support, Nonempty (connectedComponentIn D.supportᶜ x ≃ₜ Metric.ball (0 : ℂ) 1)

end Drawing

/-- The underlying multigraph of a surface map: vertices and edges are the cells. -/
noncomputable def GMap2.underlyingGraph {D : Type u} [Fintype D] [DecidableEq D]
    (G : GMap2 D) : Graph (G.Cell 0) (G.Cell 1) :=
  sorry

/-- Rotation systems of a finite multigraph: a cyclic order of the darts at each vertex. -/
def RotationSystem {α β : Type u} (Γ : Graph α β) : Type u :=
  sorry

/-- Signed rotation systems (embedding schemes), for the general-surface form. -/
def SignedRotationSystem {α β : Type u} (Γ : Graph α β) : Type u :=
  sorry

/-!
Connectivity and degree of `Graph α β` are targets shaped after the open Mathlib pull
requests (connected graphs as self-components, degree by incidence counting); the PL subclass
of drawings needs `PlanarTopology`'s triangulations; and the correspondence needs the
equivalence of drawings. Once these are pinned:

  def Graph.IsConnected (Γ : Graph α β) : Prop
  noncomputable def Graph.degree (Γ : Graph α β) (v : α) : ℕ       -- a loop counts twice
  def Drawing.IsPL (D : Drawing Γ M) : Prop      -- the support is a subcomplex of a triangulation
  def Drawing.Equiv (D D' : Drawing Γ M) : Prop

  -- Every noncrossing drawing in the interior is ambient-isotopic to a PL one:
  -- `PlanarTopology` layer 7's tameness of finite families of arcs.
  theorem Drawing.exists_isotopic_isPL (D : Drawing Γ M) (hD : D.IsNoncrossing)
      (hint : D.support ⊆ (𝓡∂ 2).interior M) : ∃ D' : Drawing Γ M, D'.IsPL ∧ AmbientIsotopic D D'

  def Drawing.toGMap2 (D : Drawing Γ M) (hpl : D.IsPL) (hc : D.IsCellular) : BundledGMap2
  def GMap2.toDrawing (G : GMap2 D) (h : IsSurfaceGMap G) : Drawing G.underlyingGraph G.realization

  -- Heffter–Edmonds–Ringel, in three forms, for connected finite multigraphs.
  theorem cellularDrawings_equiv_gmaps ...
  theorem orientedCellularDrawings_equiv_rotationSystems ...
  theorem cellularDrawings_equiv_signedRotationSystems ...

  theorem eulerFormula_cellular (D : Drawing Γ M) (hD : D.IsNoncrossing) (hc : D.IsCellular) :
      (Nat.card V(Γ) : ℤ) - Nat.card E(Γ) + D.faceCount = Surface.eulerChar M

  -- Finite branched covers and the topological Riemann–Hurwitz formula, from Euler's
  -- formula on the pulled-back cell structure; `BelyiMaps` consumes it.
  structure IsBranchedCover (p : X → Y) (B : Finset Y) (e : X → ℕ) : Prop where ...
  theorem riemannHurwitz ... :
      Surface.eulerChar X = d * Surface.eulerChar Y - ∑ x ∈ p ⁻¹' B, ((e x : ℤ) - 1)

The cellularity hypothesis is essential and should have the torus/non-disc-face
counterexample beside the implementation.
-/

/-! ## Layer 6: polygonal schemas and normal forms -/

/-- The canonical orientable schema `a₁ b₁ a₁⁻¹ b₁⁻¹ ⋯ a_g b_g a_g⁻¹ b_g⁻¹ c₁ h₁ c₁⁻¹ ⋯ c_b h_b c_b⁻¹`,
a single face with one hole block per boundary component; for `g = 0` and `b = 0` the sphere
is `a a⁻¹`, since a schema without letters has no darts. -/
noncomputable def normalFormOrientable (g b : ℕ) : PolygonalSchema :=
  sorry

/-- The canonical nonorientable schema `a₁ a₁ ⋯ a_k a_k c₁ h₁ c₁⁻¹ ⋯ c_b h_b c_b⁻¹`. -/
noncomputable def normalFormNonorientable (k : ℕ) (hk : 0 < k) (b : ℕ) : PolygonalSchema :=
  sorry

/-!
Once `PolygonalSchema.IsSurface`, `PolygonalSchema.IsConnected`, relabelling, and the
isomorphism closure are concrete, compile the elementary moves and the headline targets:

  -- `cancel` removes an adjacent pair `a a⁻¹` from a face of more than two letters; `cut`
  -- splits a face along a new label; `paste` glues two faces along a label occurring once in
  -- each; `relabel` renames or inverts a label. Boundary labels are never cancelled, cut
  -- through, or pasted along.
  inductive ElementarySchemaMove : PolygonalSchema → PolygonalSchema → Prop
  def SchemaMove := isoClosure ElementarySchemaMove
  def IsNormalForm (N : PolygonalSchema) : Prop

  -- One theorem, with or without boundary, following Gallier–Xu; connectedness is a
  -- hypothesis, since a disconnected schema reduces to several normal forms.
  theorem schema_reduces_to_normalForm (S : PolygonalSchema) (hS : S.IsSurface)
      (hc : S.IsConnected) : ∃ N, IsNormalForm N ∧ Relation.ReflTransGen SchemaMove S N

  theorem SchemaMove.realization_homeomorph (h : SchemaMove S T) :
      S.toGMap2.realization ≃ₜ T.toGMap2.realization
  theorem SchemaMove.boundaryComponentCount_eq (h : SchemaMove S T) :
      S.toGMap2.boundaryComponentCount = T.toGMap2.boundaryComponentCount
-/

/-! ## Layer 7: homology and the edge-path group of a surface map -/

/-- Three finite free modules and two matrices, from a choice of orientation of every cell. -/
structure GMap2.CellOrientations {D : Type u} [Fintype D] [DecidableEq D] (G : GMap2 D) where
  edge : ∀ e : G.Cell 1, G.EdgeOrientation e
  face : ∀ f : G.Cell 2, G.FaceOrientation f

/-- Cellular homology of a surface map, independent of the chosen orientations
(`homology_congr`). Traversing a face in its direction goes `d ↦ α₀ d` along `e(d)`, crossing
from the end of `d` to the end of `α₀ d`, and the sign is `+` when that matches the edge's
orientation; `∂₁ e = head − tail`. -/
noncomputable def GMap2.homology {D : Type u} [Fintype D] [DecidableEq D] {G : GMap2 D}
    (h : IsSurfaceGMap G) (c : G.CellOrientations) (R : Type v) [CommRing R] (i : ℕ) :
    ModuleCat.{v} R :=
  sorry

/-!
The rest of the layer waits on the realization of these modules and on a presented-group
API. Representative targets, all on `GMap2` since there is no separate cellulation type:

  theorem GMap2.d_comp_d (c : G.CellOrientations) : boundary₁ ∘ₗ boundary₂ = 0
  theorem GMap2.homology_congr (c c' : G.CellOrientations) : G.homology h c R i ≅ G.homology h c' R i
  theorem GMap2.eulerPoincare (F : Type*) [Field F] :
      G.eulerChar = ∑ i : Fin 3, (-1 : ℤ) ^ (i : ℕ) * Module.finrank F (G.homology h c F i)
  theorem GMap2.homology_two_iff_orientable ...

  def GMap2.edgePathGroup (h : IsSurfaceGMap G) (c : G.CellOrientations) : Type
  theorem GMap2.edgePathGroup_presentation ...
  theorem GMap2.abelianization_edgePathGroup :
      Abelianization (G.edgePathGroup h c) ≃* G.homology h c ℤ 1

  -- Invariance under the moves, hence under homeomorphism by `PlanarTopology`'s Pachner
  -- theorem; the action of a homeomorphism on `H₁`, the same for isotopic homeomorphisms,
  -- which layer 9 uses.
  theorem GMap2.homology_subdivideEdge ..., GMap2.homology_subdivideFace ..., GMap2.homology_flip ...
  theorem GMap2.homology_congr_homeomorph (e : G.realization ≃ₜ G'.realization) : ...
  def GMap2.homologyMap (e : G.realization ≃ₜ G'.realization) :
      G.homology h c ℤ 1 →ₗ[ℤ] G'.homology h' c' ℤ 1

  -- The normal forms, by the PID structure theorem for the rectangular boundary matrices,
  -- not the square-matrix Smith-normal-form file.
  theorem homology_normalFormOrientable_closed (g : ℕ) :
      (normalFormOrientable g 0).toGMap2.homology ℤ 1 ≅ (ℤ : Type) ^ (2 * g)
  theorem homology_normalFormNonorientable_closed (k : ℕ) (hk : 0 < k) :
      (normalFormNonorientable k hk 0).toGMap2.homology ℤ 1 ≅ (ℤ : Type) ^ (k - 1) × ZMod 2

No comparison with singular homology or with `TauCeti/AlgebraicTopology/UniversalCover/` is
targeted; invariance comes from the moves.
-/

/-! ## Layer 8: classification of compact surfaces -/

/-- The standard connected compact surfaces, including boundary. -/
inductive StandardSurface where
  | orientable (g : ℕ) (b : ℕ)
  | nonorientable (k : ℕ) (hk : 0 < k) (b : ℕ)

/-- The canonical schema of a standard surface, from layer 6. -/
noncomputable def StandardSurface.schema : StandardSurface → PolygonalSchema.{0}
  | .orientable g b => normalFormOrientable g b
  | .nonorientable k hk b => normalFormNonorientable k hk b

/-- The model of a standard surface is the realization of its canonical schema: a compact
connected surface with `b` boundary circles, fixed by the construction and not by the
classification theorem. -/
noncomputable def StandardSurface.model (S : StandardSurface) : Type :=
  S.schema.toGMap2.realization

noncomputable instance (S : StandardSurface) : TopologicalSpace S.model :=
  inferInstanceAs (TopologicalSpace S.schema.toGMap2.realization)

/-- Euler characteristic of the standard model. -/
def StandardSurface.eulerChar : StandardSurface → ℤ
  | .orientable g b => 2 - 2 * (g : ℤ) - (b : ℤ)
  | .nonorientable k _ b => 2 - (k : ℤ) - (b : ℤ)

/-- The concrete models by name. -/
abbrev Sphere2 : Type := (StandardSurface.orientable 0 0).model
abbrev Torus : Type := (StandardSurface.orientable 1 0).model
abbrev Disc : Type := (StandardSurface.orientable 0 1).model
abbrev Annulus : Type := (StandardSurface.orientable 0 2).model

/-- The named models are Mathlib's spaces. -/
example : Nonempty (Sphere2 ≃ₜ Metric.sphere (0 : EuclideanSpace ℝ (Fin 3)) 1) := by
  sorry

example : Nonempty (Disc ≃ₜ Metric.closedBall (0 : ℂ) 1) := by
  sorry

example : Nonempty (Torus ≃ₜ Circle × Circle) := by
  sorry

example : Nonempty (Annulus ≃ₜ Circle × Set.Icc (0 : ℝ) 1) := by
  sorry

section Classification

variable {M : Type*} [TopologicalSpace M] [ChartedSpace (EuclideanHalfSpace 2) M] [T2Space M]
  [CompactSpace M] [ConnectedSpace M]

/-- Existence. -/
example : ∃ S : StandardSurface, Nonempty (M ≃ₜ S.model) := by
  sorry

/-- Uniqueness. -/
example {S T : StandardSurface} (h : Nonempty (S.model ≃ₜ T.model)) : S = T := by
  sorry

/-- The library statement, in `∃!` form; a quotient-and-representative form is a bridge to
[lean-eval](https://github.com/leanprover/lean-eval) if it appears at all. -/
example : ∃! S : StandardSurface, Nonempty (M ≃ₜ S.model) := by
  sorry

end Classification

/-!
Once `PlanarTopology` supplies the three invariants, add:

  theorem homeomorph_iff_invariants :
      Nonempty (M ≃ₜ N) ↔ Surface.eulerChar M = Surface.eulerChar N ∧
        (Surface.IsOrientable M ↔ Surface.IsOrientable N) ∧
        boundaryComponentCount M = boundaryComponentCount N

  -- Genus derived from the invariants, `(2 − χ − b) / 2` or `2 − χ − b`, with the two
  -- `genus_model` lemmas saying the models have the genus their name says.
  noncomputable def Surface.genus (M : Type*) [...] [ConnectedSpace M] : ℕ
  theorem Surface.genus_model_orientable (g b : ℕ) : Surface.genus (StandardSurface.orientable g b).model = g
  theorem Surface.genus_model_nonorientable (k) (hk) (b) : ...

  -- A model with holes is the closed model of the same type minus disjoint open discs.
  theorem model_orientable_homeomorph_sdiff_discs (g b : ℕ) : ...
  theorem model_nonorientable_homeomorph_sdiff_discs (k) (hk) (b) : ...

Uniqueness must use Euler characteristic, orientability, and boundary-component count; the
boundary count is topological only after `PlanarTopology` supplies two-dimensional invariance
of domain.
-/

/-! ## Layer 9: curves, cutting, and mapping class groups -/

/-!
This layer consumes `PlanarTopology`'s isotopy, orientation, and PL vocabulary rather than
prototype private replacements. Once those types exist, pin simple closed curves and cutting,
then the groups and the comparisons:

  def SimpleClosedCurve (M : Type*) [TopologicalSpace M] : Type*
  def cutAlong (c : SimpleClosedCurve M) : Type*

  def MappingClassGroupFull (M) : Type*                        -- homeomorphisms modulo isotopy
  def MappingClassGroupRel (M) : Type*                         -- fixing the boundary pointwise
  def MappingClassGroupPlus (M) (o : Surface.Orientation M) : Type*   -- orientation-preserving

  -- The forgetful homomorphisms from the PL and smooth groups are isomorphisms, by
  -- `PlanarTopology` layer 8: surjective by isotopy to a PL homeomorphism, injective by Epstein.
  def MappingClassGroupPL.toTop (s : PLStructure M) : MappingClassGroupPL s →* MappingClassGroupFull M
  theorem MappingClassGroupPL.toTop_bijective ...
  def MappingClassGroupSmooth.toTop ... and theorem MappingClassGroupSmooth.toTop_bijective ...

  -- Base cases by the Alexander method, the twist, and the change-of-coordinates principle.
  theorem mcg_disc_rel_boundary : MappingClassGroupRel Disc ≃* Unit
  theorem mcg_annulus_rel_boundary : MappingClassGroupRel Annulus ≃* Multiplicative ℤ
  def dehnTwist (o : Surface.Orientation M) (c : SimpleClosedCurve M) (hc : IsTwoSided c) :
      MappingClassGroupPlus M o
  theorem dehnTwist_conj ..., theorem dehnTwist_eq_of_isotopic ..., theorem change_of_coordinates ...

  -- Lickorish's Lemma 2, the action on `H₁` through layer 7, and the torus.
  theorem exists_twists_reduce_intersection ...
  def MappingClassGroupFull.actH₁ : MappingClassGroupFull M →* (H₁ M ≃ₗ[ℤ] H₁ M)
  theorem mcg_torus_plus (o : Surface.Orientation Torus) :
      MappingClassGroupPlus Torus o ≃* Matrix.SpecialLinearGroup (Fin 2) ℤ

  -- The two functional Dehn–Lickorish targets, with the eponym in the docstrings.
  theorem dehnTwists_generate (o : Surface.Orientation M) (hb : (𝓡∂ 2).boundary M = ∅) :
      Subgroup.closure (Set.range (dehnTwist o)) = ⊤                       -- Lickorish 1962
  theorem exists_dehnTwist_generatingSet_card (o) (hb) (hg : 0 < Surface.genus M) :
      ∃ S : Finset (SimpleClosedCurve M), S.card = 3 * Surface.genus M - 1 ∧
        Subgroup.closure (dehnTwist o '' S) = ⊤                              -- Lickorish 1964
-/

/-! ## Layer 10: planarity -/

/-!
Planarity is combinatorial: a plane map is a rotation system of Euler characteristic two, and
the drawing characterization is layer 5's correspondence. Simple-graph theorems are stated for
`G : SimpleGraph V` with `V` finite and planarity of `Graph.ofSimpleGraph G`; minors,
topological minors, and 3-connectivity are shaped after the open Mathlib definitions. Use
descriptive Lean names and keep the historical names in docstrings:

  def PlaneMap (Γ : Graph α β) : Type* := {R : RotationSystem Γ // eulerChar R = 2}
  def Graph.IsPlanar (Γ : Graph α β) : Prop := Nonempty (PlaneMap Γ)
  theorem isPlanar_iff_exists_drawing_sphere (hΓ : Γ.IsConnected) :
      Γ.IsPlanar ↔ ∃ D : Drawing Γ Sphere2, D.IsNoncrossing
  def SimpleGraph.IsPlanar (G : SimpleGraph V) : Prop := (Graph.ofSimpleGraph G).IsPlanar

  theorem eulerFormula_plane ..., theorem edge_bound_of_isPlanar ...,
  theorem exists_vertex_degree_le_five ..., theorem not_isPlanar_K5, theorem not_isPlanar_K33

  /-- Tutte's Wheel Theorem. -/
  theorem exists_edge_delete_or_contract_isThreeConnected ...
  theorem exists_contractible_edge ...

  /-- Kuratowski's Theorem, via Thomassen's 3-connectivity induction. -/
  theorem isPlanar_iff_no_K5_K33_topologicalMinor ...

  /-- Wagner's Theorem. -/
  theorem isPlanar_iff_no_K5_K33_minor ...
  theorem isPlanar_of_isMinor ...

  /-- Tutte's Peripheral Cycle Theorem. -/
  theorem isPeripheral_iff_isFacial ...

  /-- Whitney's Unique Embedding Theorem, for 3-connected planar graphs. -/
  theorem planeMap_unique_up_to_equivalence ...

  /-- Whitney's 2-Isomorphism Theorem, for graphs without isolated vertices. -/
  theorem cycleMatroid_iso_iff_twoIsomorphic ...

  def Graph.cycleSpace ..., def Graph.cutSpace ...
  theorem cycleSpace_finrank ..., theorem cycleSpace_orthogonal_cutSpace ...
  theorem dual_cycleSpace_eq_cutSpace (P : PlaneMap Γ) : P.dual.cycleSpace = Γ.cutSpace

  -- A 2-basis means that each edge occurs in at most two basis cycles.
  def Graph.HasTwoBasis ...
  /-- Mac Lane's Planarity Criterion. -/
  theorem isPlanar_iff_hasTwoBasis ...

  /-- Fáry's Theorem, in the plane `ℂ`. -/
  theorem exists_straightLine_drawing ...
  /-- Tutte's Spring Embedding Theorem. -/
  theorem exists_convex_drawing ...
  /-- The Five Colour Theorem. -/
  theorem colorable_five_of_isPlanar (h : G.IsPlanar) : G.Colorable 5
-/

end TauCetiRoadmap.SurfaceTopology
