import Mathlib
import TauCeti.GroupTheory.SpecificGroups.CFSG.Sporadic.Presentation

/-!
# Orders of the sporadic groups from permutation representations: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is `README.md`.
The declarations here suggest Lean forms for its targets. Discharging all of them finishes neither
a work item nor the roadmap. `sorry` is allowed in this human-owned roadmap library: these are
targets, not completed definitions or proofs.

Each model is the subgroup of `Equiv.Perm (Fin n)` generated by the ATLAS standard generators,
written in Tau Ceti with `Hex.PermGroup.Kernel.permOfImages` from the `hex-perm-group-mathlib`
dependency of O0. That dependency is not available to this roadmap library, so the models are
`sorry` here.
-/

namespace TauCetiRoadmap.SporadicOrders

open TauCeti

/-- The permutation model of `M11` on 11 points, generated by its ATLAS standard generators. -/
def M11 : Subgroup (Equiv.Perm (Fin 11)) := sorry

/-- O1: the order of the model of `M11`. -/
theorem card_M11 : Nat.card M11 = 7920 := sorry

/-- O2: the presentation of `M11` maps onto its model. -/
theorem exists_surjective_M11 :
    ∃ f : SporadicName.M11.Group →* M11, Function.Surjective f := sorry

/-- O2: the presented group of `M11` is nontrivial. -/
theorem nontrivial_M11 : Nontrivial SporadicName.M11.Group := sorry

/-- The permutation model of `M12` on 12 points, generated by its ATLAS standard generators. -/
def M12 : Subgroup (Equiv.Perm (Fin 12)) := sorry

/-- O1: the order of the model of `M12`. -/
theorem card_M12 : Nat.card M12 = 95040 := sorry

/-- O2: the presentation of `M12` maps onto its model. -/
theorem exists_surjective_M12 :
    ∃ f : SporadicName.M12.Group →* M12, Function.Surjective f := sorry

/-- O2: the presented group of `M12` is nontrivial. -/
theorem nontrivial_M12 : Nontrivial SporadicName.M12.Group := sorry

/-- The permutation model of `M22` on 22 points, generated by its ATLAS standard generators. -/
def M22 : Subgroup (Equiv.Perm (Fin 22)) := sorry

/-- O1: the order of the model of `M22`. -/
theorem card_M22 : Nat.card M22 = 443520 := sorry

/-- O2: the presentation of `M22` maps onto its model. -/
theorem exists_surjective_M22 :
    ∃ f : SporadicName.M22.Group →* M22, Function.Surjective f := sorry

/-- O2: the presented group of `M22` is nontrivial. -/
theorem nontrivial_M22 : Nontrivial SporadicName.M22.Group := sorry

/-- The permutation model of `M23` on 23 points, generated by its ATLAS standard generators. -/
def M23 : Subgroup (Equiv.Perm (Fin 23)) := sorry

/-- O1: the order of the model of `M23`. -/
theorem card_M23 : Nat.card M23 = 10200960 := sorry

/-- O2: the presentation of `M23` maps onto its model. -/
theorem exists_surjective_M23 :
    ∃ f : SporadicName.M23.Group →* M23, Function.Surjective f := sorry

/-- O2: the presented group of `M23` is nontrivial. -/
theorem nontrivial_M23 : Nontrivial SporadicName.M23.Group := sorry

/-- The permutation model of `M24` on 24 points, generated by its ATLAS standard generators. -/
def M24 : Subgroup (Equiv.Perm (Fin 24)) := sorry

/-- O1: the order of the model of `M24`. -/
theorem card_M24 : Nat.card M24 = 244823040 := sorry

/-- O2: the presentation of `M24` maps onto its model. -/
theorem exists_surjective_M24 :
    ∃ f : SporadicName.M24.Group →* M24, Function.Surjective f := sorry

/-- O2: the presented group of `M24` is nontrivial. -/
theorem nontrivial_M24 : Nontrivial SporadicName.M24.Group := sorry

/-- The permutation model of `J1` on 266 points, generated by its ATLAS standard generators. -/
def J1 : Subgroup (Equiv.Perm (Fin 266)) := sorry

/-- O1: the order of the model of `J1`. -/
theorem card_J1 : Nat.card J1 = 175560 := sorry

/-- O2: the presentation of `J1` maps onto its model. -/
theorem exists_surjective_J1 :
    ∃ f : SporadicName.J1.Group →* J1, Function.Surjective f := sorry

/-- O2: the presented group of `J1` is nontrivial. -/
theorem nontrivial_J1 : Nontrivial SporadicName.J1.Group := sorry

/-- The permutation model of `J2` on 100 points, generated by its ATLAS standard generators. -/
def J2 : Subgroup (Equiv.Perm (Fin 100)) := sorry

/-- O1: the order of the model of `J2`. -/
theorem card_J2 : Nat.card J2 = 604800 := sorry

/-- O2: the presentation of `J2` maps onto its model. -/
theorem exists_surjective_J2 :
    ∃ f : SporadicName.J2.Group →* J2, Function.Surjective f := sorry

/-- O2: the presented group of `J2` is nontrivial. -/
theorem nontrivial_J2 : Nontrivial SporadicName.J2.Group := sorry

/-- The permutation model of `HS` on 100 points, generated by its ATLAS standard generators. -/
def HS : Subgroup (Equiv.Perm (Fin 100)) := sorry

/-- O1: the order of the model of `HS`. -/
theorem card_HS : Nat.card HS = 44352000 := sorry

/-- O2: the presentation of `HS` maps onto its model. -/
theorem exists_surjective_HS :
    ∃ f : SporadicName.HS.Group →* HS, Function.Surjective f := sorry

/-- O2: the presented group of `HS` is nontrivial. -/
theorem nontrivial_HS : Nontrivial SporadicName.HS.Group := sorry

/-- The permutation model of `McL` on 275 points, generated by its ATLAS standard generators. -/
def McL : Subgroup (Equiv.Perm (Fin 275)) := sorry

/-- O1: the order of the model of `McL`. -/
theorem card_McL : Nat.card McL = 898128000 := sorry

/-- O2: the presentation of `McL` maps onto its model. -/
theorem exists_surjective_McL :
    ∃ f : SporadicName.McL.Group →* McL, Function.Surjective f := sorry

/-- O2: the presented group of `McL` is nontrivial. -/
theorem nontrivial_McL : Nontrivial SporadicName.McL.Group := sorry

/-- The permutation model of `Co3` on 276 points, generated by its ATLAS standard generators. -/
def Co3 : Subgroup (Equiv.Perm (Fin 276)) := sorry

/-- O1: the order of the model of `Co3`. -/
theorem card_Co3 : Nat.card Co3 = 495766656000 := sorry

/-- O2: the presentation of `Co3` maps onto its model. -/
theorem exists_surjective_Co3 :
    ∃ f : SporadicName.Co3.Group →* Co3, Function.Surjective f := sorry

/-- O2: the presented group of `Co3` is nontrivial. -/
theorem nontrivial_Co3 : Nontrivial SporadicName.Co3.Group := sorry

end TauCetiRoadmap.SporadicOrders
