import Mathlib
import TauCeti.GroupTheory.SpecificGroups.CFSG.Sporadic.Presentation

/-!
# Orders of the sporadic groups from permutation representations: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is `README.md`.
The declarations here suggest Lean forms for its targets. Discharging all of them finishes neither
a work item nor the roadmap. `sorry` is allowed in this human-owned roadmap library: these are
targets, not completed definitions or proofs.

The signatures are given for `M24` only. Every name in the README's O1 table has the same four
declarations, with its degree, its order and its `TauCeti.SporadicName` constructor.

The model is the subgroup of `Equiv.Perm (Fin 24)` generated by the permutations of the ATLAS
files `M24G1-p24B0.m1` and `M24G1-p24B0.m2`, written in Tau Ceti with
`Hex.PermGroup.Kernel.permOfImages` from the `hex-perm-group-mathlib` dependency of O0. That
dependency is not available to this roadmap library, so the model is `sorry` here.
-/

namespace TauCetiRoadmap.SporadicOrders

open TauCeti

/-- The permutation model of `M24` on 24 points, generated by the permutations of the ATLAS files
`M24G1-p24B0.m1` and `M24G1-p24B0.m2`. -/
def M24 : Subgroup (Equiv.Perm (Fin 24)) := sorry

/-- O1: the order of the model of `M24`. -/
theorem card_M24 : Nat.card M24 = 244823040 := sorry

/-- O2: the presentation of `M24` maps onto its model. -/
theorem exists_surjective_M24 :
    ∃ f : SporadicName.M24.Group →* M24, Function.Surjective f := sorry

/-- O2: the presented group of `M24` is nontrivial. -/
theorem nontrivial_M24 : Nontrivial SporadicName.M24.Group := sorry

end TauCetiRoadmap.SporadicOrders
