import Mathlib
import TauCeti.Algebra.Group.PowMonoidHom
import TauCeti.FieldTheory.IntermediateField.Quadratic
import TauCeti.FieldTheory.SquareClassGroup.Basic
import TauCeti.NumberTheory.ClassGroup.ElementaryTwoQuotient
import TauCeti.NumberTheory.DedekindDomain.Transversal
import TauCeti.NumberTheory.EffectiveBounds.UnitSquares.Basic
import TauCeti.NumberTheory.Multiquadratic.CMField.Basic
import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Artin.Imaginary
import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Artin.Real
import TauCeti.NumberTheory.Multiquadratic.Degree
import TauCeti.NumberTheory.Multiquadratic.Frobenius
import TauCeti.NumberTheory.Multiquadratic.Galois.Basic
import TauCeti.NumberTheory.Multiquadratic.Galois.Exponent
import TauCeti.NumberTheory.Multiquadratic.Galois.Group
import TauCeti.NumberTheory.Multiquadratic.GenusField
import TauCeti.NumberTheory.Multiquadratic.MinusFive.ClassNumber
import TauCeti.NumberTheory.Multiquadratic.MinusFive.GenusField
import TauCeti.NumberTheory.Multiquadratic.MinusFive.TwoRank
import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.ClassNumber
import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.GenusField
import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.TwoRank
import TauCeti.NumberTheory.Multiquadratic.MultiquadraticSplitting
import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminants
import TauCeti.NumberTheory.Multiquadratic.Prime.Radicands
import TauCeti.NumberTheory.Multiquadratic.Quadratic.AmbiguousClassNumber
import TauCeti.NumberTheory.Multiquadratic.Quadratic.Discriminant
import TauCeti.NumberTheory.Multiquadratic.Quadratic.Ramification
import TauCeti.NumberTheory.Multiquadratic.Quadratic.TwoRank
import TauCeti.NumberTheory.Multiquadratic.SquareClass.Basic
import TauCeti.NumberTheory.Multiquadratic.SquareClass.Splitting
import TauCeti.NumberTheory.Multiquadratic.Subfield.Lattice
import TauCeti.NumberTheory.Multiquadratic.Three.ClassNumber
import TauCeti.NumberTheory.Multiquadratic.Three.TwoRank
import TauCeti.NumberTheory.Multiquadratic.Unramified.Basic
import TauCeti.NumberTheory.Multiquadratic.Unramified.NarrowGenusField
import TauCeti.NumberTheory.NumberField.NarrowClassGroup.Basic
import TauCeti.NumberTheory.NumberField.NarrowClassGroup.ElementaryTwoQuotient
import TauCeti.NumberTheory.NumberField.Units.ElementaryTwoQuotient

/-!
# Multiquadratic fields and genus theory: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is `README.md`.
The statements here suggest Lean forms for the milestones, so that contributors and reviewers
converge on names and signatures; discharging all of them finishes neither a layer nor the roadmap.

Every milestone of `README.md`, Layers 0–3 and the worked examples, has a statement here in the
form the roadmap asks for, closed by the Tau Ceti declaration that realizes it, so the
correspondence is checked by the Lean kernel rather than asserted in prose. No statement is left
unproved. That is evidence for completion, not its criterion: completion is judged by a
milestone-by-milestone audit against `README.md`, which a fully discharged file of suggested forms
cannot replace.

The earlier version of this file stated the Layer-0 and Layer-1 milestones only. The deliberate
differences between the README's requested forms and Tau Ceti's are these.

* Layer 0 assumes `[NeZero (2 : K)]`, the README's weaker option, and `[Finite ι]`, with degrees
  `2 ^ Nat.card ι`; the earlier file used `[CharZero K]` and `[Fintype ι]`. The splitting law needs
  no squarefreeness of the radicands.
* Two of the migrated erdos-unit-distance declarations follow Mathlib naming:
  `sqrtTower_finrank` is `finrank_sqrtTower`, and `index_powMonoidHom_two_le_of_closure` is
  `TauCeti.index_square_le_of_closure_eq_top`.
* The genus field is the predicate `IsGenusField d L y`: `y² = d`, `L` abelian over `ℚ`,
  unramified at every finite and infinite place over `ℚ(y)`, and root-preserving maximal. It is
  realized by `candidateGenusField`, the compositum of the `ℚ(√P)` for the prime discriminants
  `P` of `disc K`, when `d < 0`, and by its maximal totally real subfield
  `candidateGenusFieldReal` when `d > 0`. For real `K` the compositum is the *narrow* genus field
  (`IsNarrowGenusField`); the README's Layer-3 wording is corrected accordingly in this archive.
  That an arbitrary genus field is multiquadratic is the short composition
  `IsGenusField.exists_squarefree_root_adjoin_range_eq_top` below.
* The compositum is generated by square roots of the squarefree radicands of the prime
  discriminants (`-1`, `±2`, `p*` for `-4`, `±8`, `p*`). Each prime discriminant is its radicand
  or four times it, so the quadratic fields are the same.
* `Gal(K_gen/K) ≅ Cl(K)/Cl(K)²` is proved for the two constructed genus fields (and
  `≅ Cl⁺(K)/Cl⁺(K)²` for the compositum), each isomorphism compatible with the Artin map. It is
  not stated for an arbitrary `L` satisfying `IsGenusField`. Such an `L` is isomorphic to the
  constructed field by a root-preserving isomorphism (`IsGenusField.exists_algEquiv_apply_eq`), so
  the transport is routine, but Tau Ceti does not carry it out.
* In the worked examples, the ramified-prime sets `{2, 5}` and `{2, 3, 7}`, the discriminant `-84`,
  and the relative degree `[K_gen : ℚ(√-21)] = 4` are short compositions of the general theorems
  with the prime-discriminant factorizations Tau Ceti computes.

The README's *Long horizon* (explicit Kronecker–Weber beyond exponent two, the Hilbert class field,
ring class fields) is left out: the README marks it as an aspiration, not required, and says the
roadmap proper is Layers 0–3.

The Layer-0 square-class machinery is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance); the ported Tau Ceti
files credit it.
-/

namespace TauCetiRoadmap.Multiquadratic

open IntermediateField NumberField Polynomial TauCeti.Multiquadratic
open scoped NumberField IsMulCommutative nonZeroDivisors

universe u v

/-! ## Layer 0: the multiquadratic field -/

section Layer0

variable {K : Type u} {L : Type v} [Field K] [Field L] [Algebra K L]

/-- The iterated tower `K(root₀, …, rootₙ₋₁)` migrated from erdos-unit-distance. -/
example (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root n = adjoin K (root '' Set.Iio n) :=
  sqrtTower_def root n

/-- The one-step normal form behind the descent: if `x² ∈ F`, then `F(x) = F + F·x`. -/
theorem mem_sup_adjoin_sq {F : IntermediateField K L} {x : L} (hx2 : x ^ 2 ∈ F) {y : L} :
    y ∈ F ⊔ adjoin K {x} ↔ ∃ a b : L, a ∈ F ∧ b ∈ F ∧ y = a + b * x :=
  TauCeti.IntermediateField.mem_sup_adjoin_sq hx2

/-- **Layer 0, square-class descent.** If a square root of `a ∈ K` lies in `K(√d₁, …, √dₙ)`, then
`a` is a square times a subset product of the radicands. -/
theorem squareClass_of_sq_mem_fintype {ι : Type*} [Finite ι] [NeZero (2 : K)] (d : ι → K)
    (r : ι → L) (hr : ∀ i, r i ^ 2 = algebraMap K L (d i)) {a : K} {y : L}
    (hy : y ^ 2 = algebraMap K L a) (hmem : y ∈ adjoin K (Set.range r)) :
    ∃ (T : Finset ι) (s : K), a = s ^ 2 * ∏ j ∈ T, d j :=
  TauCeti.Multiquadratic.squareClass_of_sq_mem_fintype d r hr hy hmem

/-- The tower form of the descent, as migrated. -/
theorem squareClass_of_sq_mem [NeZero (2 : K)] (d : ℕ → K) (root : ℕ → L) {n : ℕ}
    (hroot : ∀ j < n, root j ^ 2 = algebraMap K L (d j)) {a : K} {y : L}
    (hy : y ^ 2 = algebraMap K L a) (hmem : y ∈ sqrtTower (K := K) root n) :
    ∃ (T : Finset ℕ) (s : K), ↑T ⊆ Set.Iio n ∧ a = s ^ 2 * ∏ j ∈ T, d j :=
  TauCeti.Multiquadratic.squareClass_of_sq_mem d root hroot hy hmem

/-- The rational-real descent `squareClass_of_sqrt_mem`, as migrated. -/
theorem squareClass_of_sqrt_mem (c : ℕ → ℚ) {n : ℕ} (hc : ∀ j < n, 0 ≤ c j) {r : ℚ} (hr : 0 ≤ r)
    (hmem : (Real.sqrt r : ℝ) ∈ sqrtTower (K := ℚ) (fun j => Real.sqrt (c j)) n) :
    ∃ (T : Finset ℕ) (s : ℚ), ↑T ⊆ Set.Iio n ∧ r = s ^ 2 * ∏ j ∈ T, c j :=
  TauCeti.Multiquadratic.squareClass_of_sqrt_mem c hc hr hmem

/-- **Layer 0, the degree.** If no nonempty subset product of the radicands is a square, then
`[K(√d₁, …, √dₙ) : K] = 2ⁿ`. -/
theorem finrank_adjoin_range {ι : Type*} [Finite ι] [NeZero (2 : K)] (d : ι → K) (r : ι → L)
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    Module.finrank K (adjoin K (Set.range r)) = 2 ^ Nat.card ι :=
  TauCeti.Multiquadratic.finrank_adjoin_range hr hindep

/-- The tower degree, migrated from `sqrtTower_finrank`. -/
theorem finrank_sqrtTower [NeZero (2 : K)] {d : ℕ → K} {root : ℕ → L}
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) (n : ℕ)
    (hindep : ∀ S : Finset ℕ, S.Nonempty → ↑S ⊆ Set.Iio n → ¬ IsSquare (∏ j ∈ S, d j)) :
    Module.finrank K (sqrtTower (K := K) root n) = 2 ^ n :=
  TauCeti.Multiquadratic.finrank_sqrtTower hroot n hindep

/-- **Square-class independence, both forms.** The classes of the radicands in `Kˣ ⧸ (Kˣ)²` are
`ZMod 2`-linearly independent iff no nonempty subset product is a square. The square-class group
is the quotient by the squares. -/
theorem linearIndependent_squareClass_iff {ι : Type*} [Finite ι] (d : ι → Kˣ) :
    LinearIndependent (ZMod 2) (fun i => TauCeti.squareClass (d i)) ↔
      ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i) :=
  TauCeti.linearIndependent_squareClass_iff d

theorem squareClass_eq_zero_iff (a : Kˣ) : TauCeti.squareClass a = 0 ↔ IsSquare a :=
  TauCeti.squareClass_eq_zero_iff a

/-- The prime-indexed corollary: distinct primes give `[ℚ(√p₁, …, √pₙ) : ℚ] = 2ⁿ`. -/
theorem finrank_adjoin_sqrt_primes {ι : Type*} [Finite ι] (p : ι → ℕ)
    (hp : ∀ i, (p i).Prime) (hinj : Function.Injective p) :
    Module.finrank ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ))) = 2 ^ Nat.card ι :=
  TauCeti.Multiquadratic.finrank_adjoin_sqrt_primes p hp hinj

/-- **Layer 0, the easy half of the Galois milestone.** A field generated by square roots of base
elements is Galois, abelian, and of exponent dividing two, with no independence hypothesis. -/
theorem isGalois {ι : Type*} [Finite ι] [NeZero (2 : K)] {d : ι → K} {r : ι → L}
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i)) : IsGalois K (adjoin K (Set.range r)) :=
  TauCeti.Multiquadratic.isGalois hr

theorem isAbelianGalois {ι : Type*} [Finite ι] [NeZero (2 : K)] {d : ι → K} {r : ι → L}
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i)) :
    IsAbelianGalois K (adjoin K (Set.range r)) :=
  TauCeti.Multiquadratic.isAbelianGalois hr

theorem aut_exponent_dvd_two {ι : Type*} {d : ι → K} {r : ι → L}
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i)) :
    Monoid.exponent (adjoin K (Set.range r) ≃ₐ[K] adjoin K (Set.range r)) ∣ 2 :=
  TauCeti.Multiquadratic.aut_exponent_dvd_two hr

/-- **Layer 0, the Galois group.** Under square-class independence, `Gal(K(√d₁, …, √dₙ)/K)` is
`(ℤ/2)ⁿ`, the vector `ε` acting as the sign change `√dᵢ ↦ (-1)^εᵢ √dᵢ`. -/
theorem exists_galoisGroupEquiv {ι : Type*} [Finite ι] [NeZero (2 : K)] {d : ι → K} {r : ι → L}
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    ∃ e : (adjoin K (Set.range r) ≃ₐ[K] adjoin K (Set.range r)) ≃* Multiplicative (ι → ZMod 2),
      ∀ (ε : ι → ZMod 2) (i : ι),
        (e.symm (Multiplicative.ofAdd ε) (gen r i) : L) = (-1) ^ (ε i).val * r i :=
  ⟨galoisGroupEquiv hr hindep, fun ε i =>
    (congrArg Subtype.val (galoisGroupEquiv_symm_apply_gen hr hindep ε i)).trans (by simp)⟩

example {ι : Type*} (r : ι → L) (i : ι) : (gen (K := K) r i : L) = r i :=
  rfl

/-- **Layer 0, the subfield lattice.** The intermediate fields correspond, order-reversingly, to the
`𝔽₂`-subspaces of `(ℤ/2)ⁿ`: a subspace `U` goes to the field fixed by the automorphisms whose sign
vector lies in `U`. -/
theorem exists_intermediateFieldEquivSubmodule {ι : Type*} [Finite ι] [NeZero (2 : K)]
    {d : ι → K} {r : ι → L} (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    ∃ e : IntermediateField K (adjoin K (Set.range r)) ≃o (Submodule (ZMod 2) (ι → ZMod 2))ᵒᵈ,
      ∀ (U : Submodule (ZMod 2) (ι → ZMod 2)) (x : adjoin K (Set.range r)),
        x ∈ e.symm (OrderDual.toDual U) ↔ ∀ σ, signPattern r σ ∈ U → σ x = x :=
  ⟨intermediateFieldEquivSubmodule hr hindep,
    mem_intermediateFieldEquivSubmodule_symm_apply_iff hr hindep⟩

theorem signPattern_eq_zero_iff {ι : Type*} {r : ι → L}
    (σ : adjoin K (Set.range r) ≃ₐ[K] adjoin K (Set.range r)) (i : ι) :
    signPattern r σ i = 0 ↔ σ (gen r i) = gen r i :=
  TauCeti.Multiquadratic.signPattern_eq_zero_iff σ i

end Layer0

/-! ## Layer 1: the prime-splitting law -/

section Layer1

/-- **Layer 1, the splitting law.** For `K = ℚ(√d₁, …, √dₙ)` with integer radicands and an odd
prime `p ∤ dⱼ`, `p` splits completely in `K` iff every `dⱼ` is a quadratic residue mod `p`. -/
theorem ncard_primesOver_multiquadratic_iff (K : Type*) [Field K] [NumberField K] {ι : Type*}
    [Finite ι] (d : ι → ℤ) (r : ι → K) (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i))
    (htop : adjoin ℚ (Set.range r) = ⊤) (p : ℕ) [Fact p.Prime] (hodd : p ≠ 2)
    (hcop : ∀ i, ¬ (p : ℤ) ∣ d i) :
    (Ideal.primesOver (Ideal.span {(p : ℤ)}) (𝓞 K)).ncard = Module.finrank ℚ K ↔
      ∀ i, legendreSym p (d i) = 1 :=
  NumberField.ncard_primesOver_multiquadratic_iff d r hr htop hodd hcop

/-- The Frobenius at `p` acts on each `√dᵢ` by the Legendre symbol `(dᵢ/p)`. -/
theorem exists_isArithFrobAt_multiquadratic (K : Type*) [Field K] [NumberField K] [IsGalois ℚ K]
    {ι : Type*} (d : ι → ℤ) (r : ι → K) (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i)) {p : ℕ}
    [Fact p.Prime] (hodd : p ≠ 2) (hcop : ∀ i, ¬ (p : ℤ) ∣ d i) (Q : Ideal (𝓞 K)) [Q.IsPrime]
    [Q.LiesOver (Ideal.span {(p : ℤ)})] :
    ∃ σ : K ≃ₐ[ℚ] K, IsArithFrobAt ℤ σ Q ∧ ∀ i, σ (r i) = legendreSym p (d i) • r i :=
  NumberField.exists_isArithFrobAt_multiquadratic d r hr hodd hcop Q

section Frobenius

variable {L : Type*} [Field L] [NumberField L] {ι : Type*} {root : ι → L} {d : ι → ℤ}

/- The rational algebra structure on the multiquadratic intermediate field, as in Tau Ceti's
`Multiquadratic.Frobenius`, where it is a local instance. -/
local instance algebraRatAdjoinRange : Algebra ℚ ↥(adjoin ℚ (Set.range root)) :=
  (adjoin ℚ (Set.range root)).algebra'

/-- **Layer 1, the Frobenius vector.** Under `Gal(ℚ(√d₁, …, √dₙ)/ℚ) ≅ (ℤ/2)ⁿ`, an arithmetic
Frobenius at a prime above an odd `p ∤ dᵢ` is the vector of Legendre symbols `((dᵢ/p))ᵢ`, written
additively. -/
theorem galoisGroupEquiv_frobenius [Finite ι] (hroot : ∀ i, root i ^ 2 = algebraMap ℤ L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, (d i : ℚ)))
    (p : ℕ) [Fact p.Prime] (hodd : p ≠ 2) (hcop : ∀ i, ¬ (p : ℤ) ∣ d i)
    (Q : Ideal (𝓞 ↥(adjoin ℚ (Set.range root)))) [Q.LiesOver (Ideal.span {(p : ℤ)})]
    {σ : ↥(adjoin ℚ (Set.range root)) ≃ₐ[ℚ] ↥(adjoin ℚ (Set.range root))}
    (hσ : IsArithFrobAt ℤ σ Q) :
    galoisGroupEquiv (fun i => by rw [hroot i, IsScalarTower.algebraMap_apply ℤ ℚ L]; simp)
        hindep σ =
      Multiplicative.ofAdd (fun i => if legendreSym p (d i) = 1 then 0 else 1) :=
  NumberField.galoisGroupEquiv_frobenius hroot hindep p hodd hcop Q hσ

end Frobenius

/-- **Rational radicands** reduce to the integral case through numerator times denominator, which
lies in the same square class. -/
theorem ncard_primesOver_multiquadratic_iff_num_mul_den (K : Type*) [Field K] [NumberField K]
    {ι : Type*} [Finite ι] {d : ι → ℚ} (r : ι → K) (hr : ∀ i, r i ^ 2 = algebraMap ℚ K (d i))
    (htop : adjoin ℚ (Set.range r) = ⊤) {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2)
    (hnum : ∀ i, ¬ (p : ℤ) ∣ (d i).num) (hden : ∀ i, ¬ p ∣ (d i).den) :
    (Ideal.primesOver (Ideal.span {(p : ℤ)}) (𝓞 K)).ncard = Module.finrank ℚ K ↔
      ∀ i, legendreSym p ((d i).num * (d i).den) = 1 :=
  TauCeti.Multiquadratic.ncard_primesOver_multiquadratic_iff_num_mul_den r hr htop hodd hnum hden

/-- **The discriminant of `ℚ(√d)`** (squarefree `d`) is `d` if `d ≡ 1 mod 4` and `4d` otherwise. -/
theorem discr_eq_fundamentalDiscriminant {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) :
    NumberField.discr K = if d % 4 = 1 then d else 4 * d := by
  rw [TauCeti.Multiquadratic.discr_eq_fundamentalDiscriminant hmin hgen hsf]
  split_ifs with h
  · exact fundamentalDiscriminant_of_mod_four_eq_one h
  · exact fundamentalDiscriminant_of_mod_four_ne_one h

/-- **The prime discriminants** are `-4`, `8`, `-8` and `p* = (-1)^((p-1)/2) p` for odd primes `p`. -/
theorem isPrimeDiscriminant_iff {D : ℤ} :
    IsPrimeDiscriminant D ↔
      (D = -4 ∨ D = 8 ∨ D = -8) ∨
        ∃ p : ℕ, p.Prime ∧ Odd p ∧ D = (-1) ^ ((p - 1) / 2) * p := by
  rw [TauCeti.Multiquadratic.isPrimeDiscriminant_iff, isEvenPrimeDiscriminant_iff]
  refine or_congr Iff.rfl (exists_congr fun p => and_congr_right fun _ =>
    and_congr_right fun hodd => ?_)
  rw [oddPrimeDiscriminant_eq_neg_one_pow_pred_div_two_mul hodd]

/-- The discriminant of a quadratic field is a product of prime discriminants, at most one of
them even: these are the generators of the genus field. -/
theorem exists_finset_primeDiscriminant_prod_eq_discr {K : Type*} [Field K] [NumberField K]
    {θ : 𝓞 K} {d : ℤ} (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) :
    ∃ s : Finset ℤ, (∀ P ∈ s, IsPrimeDiscriminant P) ∧
      (∀ P ∈ s, ∀ Q ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q) ∧
      ∏ P ∈ s, P = NumberField.discr K := by
  rw [TauCeti.Multiquadratic.discr_eq_fundamentalDiscriminant hmin hgen hsf]
  exact (isFundamentalDiscriminant_fundamentalDiscriminant hsf).exists_finset_primeDiscriminant

/-- **The conjugate-ideal transversal count**, a Dedekind-domain lemma migrated from
erdos-unit-distance: a fixed-point-free involution of a finite set `S` of primes admits at least
`2 ^ (|S| / 2)` ideals `A` with `A · σA = ∏_{p ∈ S} p`. -/
theorem exists_transversal_family {R : Type*} [CommRing R] [IsDedekindDomain R] (σ : R ≃+* R)
    (S : Finset (IsDedekindDomain.HeightOneSpectrum R))
    (hinv : ∀ p ∈ S, IsDedekindDomain.HeightOneSpectrum.equivOfRingEquiv σ p ∈ S)
    (hinvol : ∀ p ∈ S, IsDedekindDomain.HeightOneSpectrum.equivOfRingEquiv σ
      (IsDedekindDomain.HeightOneSpectrum.equivOfRingEquiv σ p) = p)
    (hfree : ∀ p ∈ S, IsDedekindDomain.HeightOneSpectrum.equivOfRingEquiv σ p ≠ p) :
    ∃ G : Finset (Ideal R), 2 ^ (S.card / 2) ≤ G.card ∧
      ∀ A ∈ G, A * Ideal.map σ A = ∏ p ∈ S, p.asIdeal :=
  TauCeti.DedekindDomain.exists_transversal_family σ S hinv hinvol hfree

end Layer1

/-! ## Layer 2: the 2-elementary quotient of the class group -/

section Layer2

/-- **The quotient `Cl(R)/Cl(R)²`.** Two classes have the same image iff their quotient is a
square, and every element is the image of a class. -/
theorem classGroup_elementaryTwoQuotientMk_eq_iff (R : Type*) [CommRing R] [IsDomain R]
    (C D : ClassGroup R) :
    TauCeti.ClassGroup.elementaryTwoQuotientMk R C =
        TauCeti.ClassGroup.elementaryTwoQuotientMk R D ↔ IsSquare (C / D) :=
  TauCeti.ClassGroup.elementaryTwoQuotientMk_eq_iff R C D

theorem classGroup_elementaryTwoQuotientMk_surjective (R : Type*) [CommRing R] [IsDomain R] :
    Function.Surjective (TauCeti.ClassGroup.elementaryTwoQuotientMk R) :=
  TauCeti.ClassGroup.elementaryTwoQuotientMk_surjective R

/-- The quotient is a different object from the `2`-torsion subgroup `Cl(R)[2]`, of the same
cardinality when the class group is finite. -/
theorem card_elementaryTwoQuotient_eq_card_twoTorsion (R : Type*) [CommRing R] [IsDomain R]
    [Finite (ClassGroup R)] :
    Nat.card (TauCeti.ClassGroup.ElementaryTwoQuotient R) =
      Nat.card {C : ClassGroup R // C ^ 2 = 1} :=
  TauCeti.ClassGroup.card_elementaryTwoQuotient_eq_card_twoTorsion R

/-- **The unit-square index**, migrated as `units_sq_index_le`: `[𝓞_F^× : (𝓞_F^×)²] ≤ 2^[F:ℚ]`,
together with its exact value `2^(rank + 1)` and the abstract input on finitely generated
commutative groups. -/
theorem units_sq_index_le (F : Type*) [Field F] [NumberField F] :
    (Subgroup.square (𝓞 F)ˣ).index ≤ 2 ^ Module.finrank ℚ F :=
  NumberField.units_sq_index_le F

theorem units_sq_index_eq (F : Type*) [Field F] [NumberField F] :
    (Subgroup.square (𝓞 F)ˣ).index = 2 ^ (Units.rank F + 1) :=
  NumberField.units_sq_index_eq F

theorem index_square_le_of_closure_eq_top {G : Type*} [CommGroup G] {S : Finset G}
    (hS : Subgroup.closure (S : Set G) = ⊤) :
    (Subgroup.square G).index ≤ 2 ^ S.card :=
  TauCeti.index_square_le_of_closure_eq_top hS

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- The nontrivial automorphism of a quadratic field `ℚ(√d) = ℚ(θ)`, on its ring of integers. -/
theorem ringOfIntegersQuadraticConj_gen (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    ringOfIntegersQuadraticConj hmin hgen θ = -θ :=
  NumberField.ringOfIntegersQuadraticConj_gen hmin hgen

/-- **The ambiguous class number formula, imaginary case.** For `d < 0` squarefree, the classes
fixed by conjugation number `2 ^ (t - 1)`, `t` the number of ramified primes. -/
theorem natCard_ambiguousClasses_of_neg (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) (hd : d < 0) :
    Nat.card {C : ClassGroup (𝓞 K) //
      ClassGroup.mulEquiv (ringOfIntegersQuadraticConj hmin hgen) C = C} =
      2 ^ ((ramifiedPrimes K).ncard - 1) :=
  natCard_mulEquiv_ringOfIntegersQuadraticConj_eq_self_eq_two_pow hmin hgen hsf hd

/-- **The narrow ambiguous class number**, for either signature: the narrow classes of ambiguous
ideals number `2 ^ (t - 1)`. -/
theorem natCard_narrowAmbiguousClasses (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) :
    Nat.card {C : NarrowClassGroup K // ∃ I : (Ideal (𝓞 K))⁰,
      Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) = (I : Ideal (𝓞 K)) ∧
        NarrowClassGroup.mk0 I = C} = 2 ^ ((ramifiedPrimes K).ncard - 1) :=
  natCard_narrowClassGroup_exists_map_ringOfIntegersQuadraticConj_eq_self_eq_two_pow hmin hgen hsf

/-- **The ambiguous class number formula, real case.** The ordinary count is `2 ^ (t - 1)` when
every prime discriminant of `disc K` is positive, and `2 ^ (t - 2)` when one is negative. -/
theorem natCard_ambiguousClasses_of_forall_pos {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hpos : ∀ P ∈ s, 0 < P) :
    Nat.card {C : ClassGroup (𝓞 K) //
      ClassGroup.mulEquiv (ringOfIntegersQuadraticConj hmin hgen) C = C} =
      2 ^ ((ramifiedPrimes K).ncard - 1) :=
  natCard_mulEquiv_ringOfIntegersQuadraticConj_eq_self_eq_two_pow_of_forall_pos hs heven hprod
    hmin hgen hsf hpos

theorem natCard_ambiguousClasses_of_neg_primeDiscriminant {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 0 < d) {P : ℤ} (hP : P ∈ s) (hneg : P < 0) :
    Nat.card {C : ClassGroup (𝓞 K) //
      ClassGroup.mulEquiv (ringOfIntegersQuadraticConj hmin hgen) C = C} =
      2 ^ ((ramifiedPrimes K).ncard - 2) :=
  natCard_mulEquiv_ringOfIntegersQuadraticConj_eq_self_eq_two_pow_of_neg hs heven hprod hmin hgen
    hsf hd hP hneg

end Layer2

/-! ## Layer 3: the genus field and the 2-rank theorem -/

section Layer3

/-- **The narrow class group** `Cl⁺(K)`: invertible fractional ideals modulo principal ideals with
a generator positive at every real place. -/
theorem narrowClassGroup_mk_eq_mk_iff {K : Type*} [Field K] [NumberField K]
    {I J : (FractionalIdeal (𝓞 K)⁰ K)ˣ} :
    NarrowClassGroup.mk I = NarrowClassGroup.mk J ↔
      ∃ x : Kˣ, (∀ (w : InfinitePlace K) (hw : w.IsReal),
          0 < InfinitePlace.embedding_of_isReal hw (x : K)) ∧
        I * toPrincipalIdeal (𝓞 K) K x = J := by
  rw [NarrowClassGroup.mk_eq_mk_iff]
  constructor
  · rintro ⟨z, hz, rfl⟩
    obtain ⟨x, hx, rfl⟩ := mem_narrowPrincipalSubgroup.mp hz
    exact ⟨x, hx, rfl⟩
  · rintro ⟨x, hx, rfl⟩
    exact ⟨_, mem_narrowPrincipalSubgroup.mpr ⟨x, hx, rfl⟩, rfl⟩

theorem narrowClassGroup_mk_surjective {K : Type*} [Field K] [NumberField K] :
    Function.Surjective
      (NarrowClassGroup.mk : (FractionalIdeal (𝓞 K)⁰ K)ˣ → NarrowClassGroup K) :=
  NarrowClassGroup.mk_surjective

/-- **The genus field**, as a predicate on an abelian extension `L/ℚ` with a chosen `y² = d`:
unramified at every finite and infinite place over `ℚ(y)`, and maximal among such extensions by a
root-preserving embedding. -/
theorem isGenusField_iff (d : ℤ) (L : Type u) [Field L] [NumberField L] (y : L) :
    IsGenusField.{u, v} d L y ↔
      y ^ 2 = algebraMap ℤ L d ∧
        Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ L) = 2 ∧
        IsAbelianGalois ℚ L ∧
        (∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ L)),
          q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 L) q) ∧
        IsUnramifiedAtInfinitePlaces (adjoin ℚ {y} : IntermediateField ℚ L) L ∧
        ∀ {M : Type v} [Field M] [NumberField M] [IsAbelianGalois ℚ M] {z : M},
          z ^ 2 = algebraMap ℤ M d →
          (∀ q : Ideal (𝓞 (adjoin ℚ {z} : IntermediateField ℚ M)),
            q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) →
          IsUnramifiedAtInfinitePlaces (adjoin ℚ {z} : IntermediateField ℚ M) M →
          ∃ φ : M →ₐ[ℚ] L, φ z = y :=
  ⟨fun h => ⟨h.root_sq, h.finrank_adjoin, h.isAbelianGalois, h.isUnramifiedAtFinitePlaces,
      h.isUnramifiedAtInfinitePlaces, h.maximal⟩,
    fun ⟨h₁, h₂, h₃, h₄, h₅, h₆⟩ => ⟨h₁, h₂, h₃, h₄, h₅, h₆⟩⟩

/-- Genus fields are unique up to a root-preserving isomorphism. -/
theorem IsGenusField.exists_algEquiv_apply_eq {d : ℤ} {L : Type u} [Field L] [NumberField L]
    {M : Type v} [Field M] [NumberField M] {y : L} {z : M} (hL : IsGenusField.{u, v} d L y)
    (hM : IsGenusField.{v, u} d M z) : ∃ e : L ≃ₐ[ℚ] M, e y = z :=
  TauCeti.Multiquadratic.IsGenusField.exists_algEquiv_apply_eq hL hM

/-- **A genus field is multiquadratic.** It is generated by square roots of square-class
independent squarefree integers, so Layer 0 applies. -/
theorem IsGenusField.exists_squarefree_root_adjoin_range_eq_top {d : ℤ} {L : Type u} [Field L]
    [NumberField L] {y : L} (hL : IsGenusField.{u, v} d L y) :
    ∃ (n : ℕ) (a : Fin n → ℤ) (root : Fin n → L),
      (∀ i, Squarefree (a i)) ∧ (∀ i, root i ^ 2 = algebraMap ℚ L (a i)) ∧
      (∀ S : Finset (Fin n), S.Nonempty → ¬ IsSquare (∏ i ∈ S, a i)) ∧
      adjoin ℚ (Set.range root) = ⊤ ∧ Module.finrank ℚ L = 2 ^ n := by
  have := hL.isAbelianGalois
  exact exists_squarefree_root_adjoin_range_eq_top_of_isUnramifiedIn_over_quadratic _
    hL.finrank_adjoin hL.isUnramifiedAtFinitePlaces

/-- **The prime-discriminant compositum.** `candidateGenusField hd ⊆ ℂ` is generated over `ℚ` by
square roots of the radicands of the prime discriminants whose product is the discriminant of
`ℚ(√d)`; each prime discriminant is its radicand or four times it. Its degree is `2 ^ t`. -/
theorem candidateGenusField_eq_adjoin {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd = adjoin ℚ (Set.range (genusFieldRoot hd)) ∧
      (∀ P, genusFieldRoot hd P ^ 2 = ((primeDiscriminantRadicand P.val : ℤ) : ℂ)) ∧
      (∀ P ∈ genusPrimeDiscriminants hd, IsPrimeDiscriminant P ∧
        (P = primeDiscriminantRadicand P ∨ P = 4 * primeDiscriminantRadicand P)) ∧
      ∏ P ∈ genusPrimeDiscriminants hd, P = fundamentalDiscriminant d :=
  ⟨candidateGenusField_def hd, genusFieldRoot_sq hd,
    fun P hP => ⟨(genusPrimeDiscriminants_spec hd).1 P hP,
      primeDiscriminant_eq_radicand_or_eq_four_mul_radicand
        ((genusPrimeDiscriminants_spec hd).1 P hP)⟩,
    (genusPrimeDiscriminants_spec hd).2.2⟩

theorem finrank_candidateGenusField {d : ℤ} (hd : Squarefree d) :
    Module.finrank ℚ (candidateGenusField hd) = 2 ^ (genusPrimeDiscriminants hd).card :=
  TauCeti.Multiquadratic.finrank_candidateGenusField hd

/-- The embedded copy `K = ℚ(√d)` of the base, generated by a chosen square root of `d`. -/
theorem candidateGenusFieldBase_def {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBase hd = adjoin ℚ {candidateGenusFieldBaseRoot hd} ∧
      candidateGenusFieldBaseRoot hd ^ 2 =
        algebraMap ℚ (candidateGenusField hd) ((d : ℤ) : ℚ) :=
  ⟨TauCeti.Multiquadratic.candidateGenusFieldBase_def hd, candidateGenusFieldBaseRoot_sq hd⟩

/-- **Layer 3, the genus field of an imaginary quadratic field** is the prime-discriminant
compositum. -/
theorem isGenusField_candidateGenusField {d : ℤ} (hd : Squarefree d) (hneg : d < 0) :
    IsGenusField.{0, v} d (candidateGenusField hd) (candidateGenusFieldBaseRoot hd) :=
  TauCeti.Multiquadratic.isGenusField_candidateGenusField hd hneg

/-- **The narrow genus field** (unramified at the finite places only, maximal among such abelian
extensions) of `ℚ(√d)` is the prime-discriminant compositum, for either signature. -/
theorem isNarrowGenusField_iff (d : ℤ) (L : Type u) [Field L] [NumberField L] (y : L) :
    IsNarrowGenusField d L y ↔
      y ^ 2 = algebraMap ℤ L d ∧
        Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ L) = 2 ∧
        IsAbelianGalois ℚ L ∧
        (∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ L)),
          q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 L) q) ∧
        ∀ {M : Type u} [Field M] [NumberField M] [IsAbelianGalois ℚ M] {z : M},
          z ^ 2 = algebraMap ℤ M d →
          (∀ q : Ideal (𝓞 (adjoin ℚ {z} : IntermediateField ℚ M)),
            q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) →
          Nonempty (M →ₐ[ℚ] L) :=
  ⟨fun h => ⟨h.root_sq, h.finrank_adjoin, h.isAbelianGalois, h.isUnramifiedAtFinitePlaces,
      h.maximal⟩,
    fun ⟨h₁, h₂, h₃, h₄, h₅⟩ => ⟨h₁, h₂, h₃, h₄, h₅⟩⟩

theorem isNarrowGenusField_candidateGenusField {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    IsNarrowGenusField d (candidateGenusField hd) (candidateGenusFieldBaseRoot hd) :=
  TauCeti.Multiquadratic.isNarrowGenusField_candidateGenusField hd hnsq

/-- **Layer 3, the genus field of a real quadratic field** is the maximal totally real subfield of
the prime-discriminant compositum: the elements fixed by complex conjugation under every
embedding into `ℂ`. -/
theorem mem_candidateGenusFieldReal_iff {d : ℤ} (hd : Squarefree d)
    (x : candidateGenusField hd) :
    x ∈ candidateGenusFieldReal hd ↔ ∀ φ : candidateGenusField hd →+* ℂ, star (φ x) = φ x :=
  TauCeti.Multiquadratic.mem_candidateGenusFieldReal_iff hd x

theorem isGenusField_candidateGenusFieldReal {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d) :
    IsGenusField.{0, v} d (candidateGenusFieldReal hd)
      (candidateGenusFieldRealBaseRoot hd hpos) :=
  TauCeti.Multiquadratic.isGenusField_candidateGenusFieldReal hd hnsq hpos

/-- **Layer 3, `Gal(K_gen/K) ≅ Cl(K)/Cl(K)²` for imaginary `K`**, carrying the Artin automorphism
of an ideal prime to any finite set of primes to its class modulo squares. -/
theorem exists_autCandidateGenusFieldEquivElementaryTwoQuotient {d : ℤ} (hd : Squarefree d)
    (hneg : d < 0) :
    ∃ e : (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) ≃*
        Multiplicative
          (TauCeti.ClassGroup.ElementaryTwoQuotient (𝓞 (candidateGenusFieldBase hd))),
      ∀ (S : Finset (IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))))
        (I : TauCeti.NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S),
        e (TauCeti.NumberFieldArithmetic.artinHomAway IsMulCommutative.is_comm.comm S
            (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd
              (not_isSquare_of_neg (by exact_mod_cast hneg)) v.asIdeal Q
              inferInstance inferInstance) I) =
          Multiplicative.ofAdd (TauCeti.elementaryTwoQuotientMk
            (ClassGroup.mk (candidateGenusFieldBase hd)
              (I : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
                (candidateGenusFieldBase hd))ˣ))) :=
  ⟨_, autCandidateGenusFieldEquivElementaryTwoQuotient_artinHomAway hd hneg⟩

/-- **Layer 3, `Gal(K_gen/K) ≅ Cl(K)/Cl(K)²` for real `K`**, with `K_gen` the maximal totally real
subfield of the compositum, compatibly with the Artin map. -/
theorem exists_autCandidateGenusFieldRealEquivElementaryTwoQuotient {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    letI := candidateGenusFieldRealIsScalarTower hd hpos
    letI := isAbelianGalois_candidateGenusFieldReal_over_base hd hpos
    ∃ e : (candidateGenusFieldReal hd ≃ₐ[candidateGenusFieldBase hd]
          candidateGenusFieldReal hd) ≃*
        Multiplicative
          (TauCeti.ClassGroup.ElementaryTwoQuotient (𝓞 (candidateGenusFieldBase hd))),
      ∀ (S : Finset (IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))))
        (I : TauCeti.NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S),
        e (TauCeti.NumberFieldArithmetic.artinHomAway (L := candidateGenusFieldReal hd)
            (fun σ τ ↦ (commute_iff_eq σ τ).2 (IsMulCommutative.is_comm.comm σ τ)) S
            (isUnramifiedAway_of_intermediateField (candidateGenusFieldReal hd) S
              (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
                inferInstance inferInstance)) I) =
          Multiplicative.ofAdd (TauCeti.elementaryTwoQuotientMk
            (ClassGroup.mk (candidateGenusFieldBase hd)
              (I : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
                (candidateGenusFieldBase hd))ˣ))) :=
  ⟨_, autCandidateGenusFieldRealEquivElementaryTwoQuotient_artinHomAway hd hnsq hpos⟩

/-- **The narrow form**, for either signature: `Gal(K_gen⁺/K) ≅ Cl⁺(K)/Cl⁺(K)²` for the
prime-discriminant compositum, compatibly with the Artin map. -/
theorem exists_autCandidateGenusFieldEquivNarrowElementaryTwoQuotient {d : ℤ}
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    ∃ e : (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) ≃*
        Multiplicative (NarrowClassGroup.ElementaryTwoQuotient (candidateGenusFieldBase hd)),
      ∀ (S : Finset (IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))))
        (I : TauCeti.NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S),
        e (TauCeti.NumberFieldArithmetic.artinHomAway IsMulCommutative.is_comm.comm S
            (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
              inferInstance inferInstance) I) =
          Multiplicative.ofAdd (TauCeti.elementaryTwoQuotientMk
            (NarrowClassGroup.mk (I : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
              (candidateGenusFieldBase hd))ˣ))) :=
  ⟨_, autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway hd hnsq⟩

/-- `t` is the number of ramified rational primes, one for each prime discriminant of `disc K`. -/
theorem mem_ramifiedPrimes_iff {K : Type*} [Field K] {p : ℕ} :
    p ∈ ramifiedPrimes K ↔ p.Prime ∧ ¬ Algebra.IsUnramifiedIn (𝓞 K) (Ideal.span {(p : ℤ)}) :=
  NumberField.mem_ramifiedPrimes_iff

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

theorem ncard_ramifiedPrimes_eq_card (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ Q ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q)
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d) :
    (ramifiedPrimes K).ncard = s.card :=
  TauCeti.Multiquadratic.ncard_ramifiedPrimes_eq_card hmin hgen hsf hs heven hprod

/-- The `2`-rank is the `ZMod 2`-dimension of `Cl/Cl²`, ordinary or narrow. -/
theorem classGroup_twoRank_def (R : Type*) [CommRing R] [IsDomain R] :
    TauCeti.ClassGroup.twoRank R =
      Module.finrank (ZMod 2) (TauCeti.ClassGroup.ElementaryTwoQuotient R) :=
  TauCeti.ClassGroup.twoRank_def R

theorem narrowClassGroup_twoRank_def :
    NarrowClassGroup.twoRank K =
      Module.finrank (ZMod 2) (NarrowClassGroup.ElementaryTwoQuotient K) :=
  NarrowClassGroup.twoRank_def K

/-- **Layer 3, the `2`-rank formula for imaginary `K`:** `2-rank Cl(K) = t - 1`. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) (hd : d < 0) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 :=
  TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf hd

/-- **Layer 3, the narrow `2`-rank formula** `2-rank Cl⁺(K) = t - 1`, for either signature. -/
theorem narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) :
    NarrowClassGroup.twoRank K = (ramifiedPrimes K).ncard - 1 :=
  TauCeti.Multiquadratic.narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf

/-- For imaginary `K` the narrow and ordinary `2`-ranks agree. -/
theorem narrowTwoRank_eq_classGroupTwoRank [IsTotallyComplex K] :
    NarrowClassGroup.twoRank K = TauCeti.ClassGroup.twoRank (𝓞 K) :=
  NarrowClassGroup.twoRank_eq_classGroupTwoRank K

/-- For real `K` the ordinary `2`-rank is `t - 1` or `t - 2`. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one_or_sub_two (hK : Module.finrank ℚ K = 2) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 ∨
      TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 2 :=
  TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one_or_sub_two hK

/-- **The ordinary `2`-rank drops for `ℚ(√3)`:** `t = 2` and class number `1`, so the ordinary
`2`-rank is `0`, while the narrow `2`-rank is `1 = t - 1` and the narrow class number is `2`. -/
theorem sqrt_three (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ))
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    (ramifiedPrimes K).ncard = 2 ∧ NumberField.classNumber K = 1 ∧
      TauCeti.ClassGroup.twoRank (𝓞 K) = 0 ∧ NarrowClassGroup.twoRank K = 1 ∧
      Nat.card (NarrowClassGroup K) = 2 :=
  ⟨ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen,
    TauCeti.NumberField.classNumber_eq_one_of_minpoly_eq_X_sq_sub_three hmin hgen,
    twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three hmin hgen,
    narrowTwoRank_eq_one_of_minpoly_eq_X_sq_sub_three hmin hgen,
    natCard_narrowClassGroup_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen⟩

end Layer3

/-! ## Worked examples -/

section Examples

/-- **`[ℚ(√2, √3) : ℚ] = 4`.** -/
example :
    Module.finrank ℚ (adjoin ℚ {Real.sqrt 2, Real.sqrt 3} : IntermediateField ℚ ℝ) = 4 :=
  finrank_adjoin_sqrt_two_three

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

/-- **`ℚ(√-5)`** has class number `2`, ramified primes `2` and `5`, and `2`-rank `1 = t - 1`. -/
theorem sqrt_neg_five (hmin : minpoly ℤ θ = X ^ 2 - C (-5 : ℤ))
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    NumberField.classNumber K = 2 ∧ ramifiedPrimes K = {2, 5} ∧
      TauCeti.ClassGroup.twoRank (𝓞 K) = 1 ∧
      TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 := by
  have hd : Squarefree (-5 : ℤ) := (Int.prime_iff_natAbs_prime.mpr (by decide)).squarefree
  obtain ⟨hs, -, hprod⟩ := genusPrimeDiscriminants_spec hd
  rw [genusPrimeDiscriminants_neg_five] at hs hprod
  refine ⟨TauCeti.NumberField.classNumber_eq_two_of_minpoly_eq_X_sq_add_five hmin hgen, ?_,
    twoRank_eq_one_of_minpoly_eq_X_sq_add_five hmin hgen,
    TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hd (by norm_num)⟩
  rw [ramifiedPrimes_eq_image hmin hgen hd hs hprod]
  simp [primeDiscriminantPrime_def]

/-- The genus field of `ℚ(√-5)` is `ℚ(i, √5)`. -/
theorem exists_isGenusField_adjoin_I_sqrt_five :
    ∃ y : adjoin ℚ ({Complex.I, (Real.sqrt 5 : ℂ)} : Set ℂ),
      IsGenusField.{0, v} (-5) (adjoin ℚ ({Complex.I, (Real.sqrt 5 : ℂ)} : Set ℂ)) y :=
  TauCeti.Multiquadratic.exists_isGenusField_adjoin_I_sqrt_five

/-- **`ℚ(√-21)`** has discriminant `-84`, class group `(ℤ/2)²`, ramified primes `2`, `3`, `7`, and
`2`-rank `2 = t - 1`. -/
theorem sqrt_neg_twenty_one (hmin : minpoly ℤ θ = X ^ 2 - C (-21 : ℤ))
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    NumberField.discr K = -84 ∧
      Nonempty (ClassGroup (𝓞 K) ≃* Multiplicative (ZMod 2 × ZMod 2)) ∧
      ramifiedPrimes K = {2, 3, 7} ∧ TauCeti.ClassGroup.twoRank (𝓞 K) = 2 ∧
      TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 := by
  have hd := squarefree_neg_twenty_one
  obtain ⟨hs, -, hprod⟩ := genusPrimeDiscriminants_spec hd
  rw [genusPrimeDiscriminants_neg_twenty_one] at hs hprod
  refine ⟨?_,
    nonempty_classGroup_mulEquiv_zmod_two_sq_of_minpoly_eq_X_sq_add_twenty_one hmin hgen, ?_,
    twoRank_eq_two_of_minpoly_eq_X_sq_add_twenty_one hmin hgen,
    TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hd (by norm_num)⟩
  · rw [discr_eq_fundamentalDiscriminant hmin hgen hd]
    norm_num
  · rw [ramifiedPrimes_eq_image hmin hgen hd hs hprod]
    simp [primeDiscriminantPrime_def]

/-- The genus field of `ℚ(√-21)` is `ℚ(i, √-3, √-7)`, of degree `4` over `ℚ(√-21)`. -/
theorem exists_isGenusField_adjoin_I_sqrt_neg_three_sqrt_neg_seven :
    ∃ y : adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ),
      IsGenusField.{0, v} (-21) (adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ)) y :=
  TauCeti.Multiquadratic.exists_isGenusField_adjoin_I_sqrt_neg_three_sqrt_neg_seven

example : sqrtNegThree ^ 2 = -3 ∧ sqrtNegSeven ^ 2 = -7 :=
  ⟨sqrtNegThree_sq, sqrtNegSeven_sq⟩

theorem finrank_candidateGenusField_neg_twenty_one :
    candidateGenusField squarefree_neg_twenty_one =
        adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ) ∧
      Module.finrank (candidateGenusFieldBase squarefree_neg_twenty_one)
        (candidateGenusField squarefree_neg_twenty_one) = 4 := by
  refine ⟨candidateGenusField_neg_twenty_one_eq, ?_⟩
  rw [finrank_candidateGenusField_over_candidateGenusFieldBase _
      (not_isSquare_of_neg (by norm_num)),
    genusPrimeDiscriminants_neg_twenty_one]
  rfl

/-- **The erdos CM field** `ℚ(i, √q₀, …, √q_{g-1})`, for distinct primes `qⱼ`, is a multiquadratic
field of degree `2^{g+1}`. -/
theorem finrank_adjoin_I_sqrt_primes {ι : Type*} [Finite ι] (p : ι → ℕ)
    (hp : ∀ i, (p i).Prime) (hinj : Function.Injective p) :
    Module.finrank ℚ
        (adjoin ℚ (insert Complex.I (Set.range fun i => ((Real.sqrt (p i) : ℝ) : ℂ))))
      = 2 ^ (Nat.card ι + 1) :=
  TauCeti.Multiquadratic.finrank_adjoin_I_sqrt_primes p hp hinj

end Examples

end TauCetiRoadmap.Multiquadratic
