import Mathlib.FieldTheory.IsAlgClosed.Basic
import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.DiagramAutomorphism
import TauCeti.LinearAlgebra.RootSystem.Isogeny.Special
import TauCeti.GroupTheory.TitsSystem.Basic

/-!
# Chevalley groups and the Chevalley–Demazure group schemes: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive document is `README.md`.
The declarations here suggest Lean forms for the points of the simply connected Chevalley group of
a valid Dynkin type and the maps between them. Discharging all of them finishes neither a work item
nor the roadmap. `sorry` is allowed in this human-owned roadmap library: these are targets, not
completed definitions or proofs.

The group scheme itself, the Chevalley datum structure, and the big-cell statements are specified in
`README.md` against the existing generic toral-closure API; they are not displayed here. What is
displayed is the interface on points that downstream roadmaps consume: root subgroups, the torus,
the elementary subgroup, and the endomorphisms with their character maps.
-/

namespace TauCetiRoadmap.ChevalleyGroups

open TauCeti

variable (t : DynkinType) (ht : t.Valid)

/-! ## C2: points, root subgroups, and the torus -/

/-- The points over `A` of the simply connected Chevalley–Demazure group scheme of `t`, built as the
Kostant toral closure of the direct sum of the fundamental modules with their admissible lattices. -/
def ChevalleyGroup (t : DynkinType) (_ht : t.Valid) (A : Type) [CommRing A] : Type := sorry

instance (A : Type) [CommRing A] : Group (ChevalleyGroup t ht A) := sorry

/-- The root subgroup `u ↦ x_α(u)` for every root `α`, in the enumeration of
`DynkinType.simplyConnectedRootDatum`. -/
def rootSubgroup (A : Type) [CommRing A] (α : Fin t.numRoots) :
    Multiplicative A →* ChevalleyGroup t ht A := sorry

/-- The split maximal torus, with coordinates indexed by the fundamental weights. -/
def torus (A : Type) [CommRing A] : (Fin t.rank → Aˣ) →* ChevalleyGroup t ht A := sorry

/-- The pinning equation `s x_α(u) s⁻¹ = x_α(α(s) u)`, with `α` read as a character in the weight
lattice of `DynkinType.simplyConnectedRootDatum`. -/
theorem torus_conj_rootSubgroup (A : Type) [CommRing A] (s : Fin t.rank → Aˣ)
    (α : Fin t.numRoots) (u : A) :
    torus t ht A s * rootSubgroup t ht A α (.ofAdd u) * (torus t ht A s)⁻¹ =
      rootSubgroup t ht A α
        (.ofAdd ((∏ i, ((s i : Aˣ) ^ ((t.simplyConnectedRootDatum ht).root α i) : Aˣ) : A) * u)) :=
  sorry

/-! ## C3 and C4: the group over a field -/

/-- The subgroup generated by the root subgroups. -/
def elementary (k : Type) [Field k] : Subgroup (ChevalleyGroup t ht k) :=
  Subgroup.closure (⋃ α, Set.range (rootSubgroup t ht k α))

/-- Over an algebraically closed field every point is generated by root subgroups (C4). -/
theorem elementary_eq_top (k : Type) [Field k] [IsAlgClosed k] : elementary t ht k = ⊤ := sorry

/-- The Tits system of the elementary group: `B = U T`, `N` generated by `T` and the Weyl
representatives, and the simple reflections of the pinned base (C3). -/
def titsSystem (k : Type) [Field k] : TitsSystem (elementary t ht k) := sorry

/-! ## C5: endomorphisms and their character maps -/

/-- The pullback of characters along an endomorphism mapping the torus into itself. Over an
algebraically closed field the induced map on the torus is given by a unique integer matrix; over a
finite field the torus can be trivial, so no such map is defined there. -/
def characterMap {k : Type} [Field k] [IsAlgClosed k] (F : ChevalleyGroup t ht k →* ChevalleyGroup t ht k)
    (hF : ∀ s, ∃ s', F (torus t ht k s) = torus t ht k s') :
    (Fin t.rank → ℤ) →+ (Fin t.rank → ℤ) := sorry

/-- The graph automorphism of a diagram symmetry, induced by the numbered symmetry of the
full-weight module. -/
def graphAut (k : Type) [Field k] {σ : Equiv.Perm (Fin t.rank)} (hσ : σ ∈ t.diagramSymmetry) :
    ChevalleyGroup t ht k ≃* ChevalleyGroup t ht k := sorry

/-- `γ_σ (x_{α_i}(u)) = x_{α_{σ i}}(u)` on the positive simple root subgroups. The same equation holds
on the negative simple root subgroups, and the two together determine `γ_σ`: the positive ones
alone do not, since conjugation by a highest-root element fixes each of them. -/
theorem graphAut_rootSubgroup_simpleIndex (k : Type) [Field k] {σ : Equiv.Perm (Fin t.rank)}
    (hσ : σ ∈ t.diagramSymmetry) (i : Fin t.rank) (u : Multiplicative k) :
    graphAut t ht k hσ (rootSubgroup t ht k (t.simpleIndex ht i) u) =
      rootSubgroup t ht k (t.simpleIndex ht (σ i)) u := sorry

end TauCetiRoadmap.ChevalleyGroups
