import Mathlib
import TauCetiRoadmap.NumberFieldArithmetic.Suggested

/-!
# Global number fields, ray classes, adeles, and Hecke characters: target signatures

**This file is not the roadmap and is not exhaustive.** The definitive specification is
`README.md`. These declarations pin the shared carriers and the three consumer-required theorem
names. Statements needing unsettled implementation API remain in the README rather than being
represented by fake interface structures.

Number Field Arithmetic owns `idealsAway` and the finite-completion dictionary. The abbreviation
below consumes that ideal group directly. This file contains no Artin map, reciprocity map, or class
field.
-/

namespace TauCetiRoadmap.GlobalNumberFields

open Asymptotics Complex Filter NumberField Topology
open IsDedekindDomain (HeightOneSpectrum)
open scoped nonZeroDivisors

universe u

variable {K : Type u} [Field K] [NumberField K]

/-! ## Layers 0--1: places and weak approximation -/

/-- **Layer 1, mixed-place Artin--Whaples weak approximation.** The diagonal image of `K` is
dense in a finite product of finite and infinite completions. Both products are genuinely present;
the theorem is not merely Mathlib's all-infinite-place result or a finite congruence corollary.

This exact name is consumed by Global Quadratic Forms. -/
theorem weakApproximation_denseRange
    (S : Finset (HeightOneSpectrum (𝓞 K))) (T : Finset (InfinitePlace K)) :
    DenseRange (fun x : K =>
      ((fun v : {v // v ∈ S} => algebraMap K (v.1.adicCompletion K) x),
        fun w : {w // w ∈ T} => algebraMap K w.1.Completion x)) := sorry

/-! ## Layer 2: moduli and ray classes -/

/-- A modulus is a nonzero integral ideal and a finite set of real places. -/
structure Modulus (K : Type u) [Field K] [NumberField K] where
  finitePart : Ideal (𝓞 K)
  finitePart_ne_bot : finitePart ≠ ⊥
  infinitePart : Finset {w : InfinitePlace K // w.IsReal}

instance : Dvd (Modulus K) :=
  ⟨fun 𝔪 𝔫 => 𝔪.finitePart ∣ 𝔫.finitePart ∧ 𝔪.infinitePart ⊆ 𝔫.infinitePart⟩

/-- The finite support of a modulus. -/
noncomputable def Modulus.support (𝔪 : Modulus K) : Finset (HeightOneSpectrum (𝓞 K)) := sorry

/-- The exponent of a finite place in a modulus. -/
noncomputable def Modulus.exponent (𝔪 : Modulus K) (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  (Associates.mk v.asIdeal).count (Associates.mk 𝔪.finitePart).factors

def Modulus.one (K : Type u) [Field K] [NumberField K] : Modulus K where
  finitePart := ⊤
  finitePart_ne_bot := top_ne_bot
  infinitePart := ∅

theorem Modulus.one_dvd (𝔪 : Modulus K) : Modulus.one K ∣ 𝔪 := sorry

noncomputable def narrowModulus (K : Type u) [Field K] [NumberField K] : Modulus K := by
  letI : Fintype {w : InfinitePlace K // w.IsReal} := Fintype.ofFinite _
  exact
    { finitePart := ⊤
      finitePart_ne_bot := top_ne_bot
      infinitePart := Finset.univ }

/-- Multiplicative congruence, including positivity at the real part of the modulus. -/
def IsCongrOne (𝔪 : Modulus K) (x : Kˣ) : Prop :=
  (∀ v : HeightOneSpectrum (𝓞 K), v.asIdeal ∣ 𝔪.finitePart →
      v.valuation K ((x : K) - 1) ≤
        ((Multiplicative.ofAdd (-(𝔪.exponent v : ℤ)) : Multiplicative ℤ) :
          WithZero (Multiplicative ℤ))) ∧
    ∀ w ∈ 𝔪.infinitePart, 0 < InfinitePlace.embedding_of_isReal w.2 (x : K)

def congruenceSubgroup (𝔪 : Modulus K) : Subgroup Kˣ where
  carrier := {x | IsCongrOne 𝔪 x}
  mul_mem' := by sorry
  one_mem' := by sorry
  inv_mem' := by sorry

/-- Elements of `Kˣ` that are units at every finite place dividing the modulus. This is the
domain of reduction to residue units; it is not merely a predicate hidden inside that map. -/
def primeToSubgroup (m : Modulus K) : Subgroup Kˣ where
  carrier := {x | ∀ v : HeightOneSpectrum (𝓞 K), v.asIdeal ∣ m.finitePart →
    v.valuation K (x : K) = 1}
  mul_mem' := by sorry
  one_mem' := by sorry
  inv_mem' := by sorry

/-- Units of the ring of integers congruent to one modulo the finite and real parts of the
modulus. Its index is the unit correction in the ray-class number formula. -/
def unitsCongruenceSubgroup (m : Modulus K) : Subgroup (𝓞 K)ˣ :=
  (congruenceSubgroup m).comap (Units.map (algebraMap (𝓞 K) K).toMonoidHom)

/-- **Single ownership of the prime-to ideal group.** -/
noncomputable abbrev idealsPrimeTo (𝔪 : Modulus K) :=
  TauCetiRoadmap.NumberFieldArithmetic.idealsAway (K := K) 𝔪.support

/-- The ray of principal ideals generated by elements congruent to one. -/
noncomputable def ray (𝔪 : Modulus K) : Subgroup (idealsPrimeTo 𝔪) := sorry

def RayClassGroup (𝔪 : Modulus K) : Type u :=
  idealsPrimeTo 𝔪 ⧸ ray 𝔪

noncomputable instance (𝔪 : Modulus K) : CommGroup (RayClassGroup 𝔪) :=
  inferInstanceAs (CommGroup (idealsPrimeTo 𝔪 ⧸ ray 𝔪))

/-- Coprimality of a nonzero integral ideal to the finite part. -/
def Modulus.IsCoprimeTo (𝔪 : Modulus K) (I : Ideal (𝓞 K)) : Prop :=
  I ≠ ⊥ ∧ ∀ v : HeightOneSpectrum (𝓞 K), v ∈ 𝔪.support → ¬ v.asIdeal ∣ I

noncomputable def idealClass (𝔪 : Modulus K) (I : Ideal (𝓞 K)) : RayClassGroup 𝔪 := sorry

theorem idealClass_mul (𝔪 : Modulus K) {I J : Ideal (𝓞 K)}
    (hI : 𝔪.IsCoprimeTo I) (hJ : 𝔪.IsCoprimeTo J) :
    idealClass 𝔪 (I * J) = idealClass 𝔪 I * idealClass 𝔪 J := sorry

theorem idealClass_surjective (𝔪 : Modulus K) (c : RayClassGroup 𝔪) :
    ∃ I : Ideal (𝓞 K), 𝔪.IsCoprimeTo I ∧ idealClass 𝔪 I = c := sorry

theorem finite_rayClassGroup (𝔪 : Modulus K) : Finite (RayClassGroup 𝔪) := sorry

noncomputable def classMap {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) :
    RayClassGroup 𝔫 →* RayClassGroup 𝔪 := sorry

theorem classMap_idealClass {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) {I : Ideal (𝓞 K)}
    (hI : 𝔫.IsCoprimeTo I) : classMap h (idealClass 𝔫 I) = idealClass 𝔪 I := sorry

theorem classMap_surjective {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) :
    Function.Surjective (classMap h) := sorry

/-- The canonical ideal-class map kills exactly the ray-principal ideals. Keeping the
triviality criterion named prevents consumers from replacing factorization through the ray
class group by an unstructured hypothesis on an ideal weight. -/
theorem idealClass_eq_one_iff (m : Modulus K) {I : Ideal (𝓞 K)}
    (hI : m.IsCoprimeTo I) :
    idealClass m I = 1 ↔
      ∃ a b : 𝓞 K, a ≠ 0 ∧ b ≠ 0 ∧ a - 1 ∈ m.finitePart ∧ b - 1 ∈ m.finitePart ∧
        (∀ w ∈ m.infinitePart,
          0 < InfinitePlace.embedding_of_isReal w.2 (algebraMap (𝓞 K) K a)) ∧
        (∀ w ∈ m.infinitePart,
          0 < InfinitePlace.embedding_of_isReal w.2 (algebraMap (𝓞 K) K b)) ∧
        I * Ideal.span {b} = Ideal.span {a} := sorry

/-- Reduction on residue-field units along divisibility of moduli. The direction is from the
larger modulus to the smaller one, matching `classMap`; this is a units pullback and not a
ring-level inverse. -/
noncomputable def finiteUnitsMap {m n : Modulus K} (h : m ∣ n) :
    ((𝓞 K) ⧸ n.finitePart)ˣ →* ((𝓞 K) ⧸ m.finitePart)ˣ :=
  Units.map (Ideal.Quotient.factor (Ideal.le_of_dvd h.1)).toMonoidHom

/-! ## Layer 3: ray-class counting -/

open scoped Classical in
/-- The number of nonzero integral ideals in one ray class with norm at most `x`. The subtype
contains the coprimality and class conditions, so the zero ideal and other classes cannot enter. -/
noncomputable def rayClassIdealCountingFunction
    (𝔪 : Modulus K) (c : RayClassGroup 𝔪) (x : ℝ) : ℕ :=
  Nat.card {I : Ideal (𝓞 K) // 𝔪.IsCoprimeTo I ∧ idealClass 𝔪 I = c ∧
    (Ideal.absNorm I : ℝ) ≤ x}

/-- The positive coefficient common to every ray class. Its explicit formula is the Dedekind-zeta
residue times the Euler factors at the finite support, divided by `#Cl_𝔪`. -/
noncomputable def rayClassIdealMainTerm (𝔪 : Modulus K) : ℝ := sorry

theorem rayClassIdealMainTerm_pos (𝔪 : Modulus K) : 0 < rayClassIdealMainTerm 𝔪 := sorry

/-- **Exact Chebotarev contract: uniform ray-class ideal counting.** One positive power-saving
exponent works for every member of the finite ray class group. -/
theorem rayClassIdealCount (𝔪 : Modulus K) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ c : RayClassGroup 𝔪,
      (fun x : ℝ =>
          (rayClassIdealCountingFunction 𝔪 c x : ℝ) - rayClassIdealMainTerm 𝔪 * x) =O[atTop]
        (fun x : ℝ => x ^ (1 - δ)) := sorry

/-! ## Layer 9 dependency: character carriers -/

/- The carrier is placed before the partial-sum contract because the theorem is arithmetic and
does not depend on the later idelic realization. -/
abbrev RayClassCharacter (𝔪 : Modulus K) := RayClassGroup 𝔪 →* ℂˣ

open scoped Classical in
noncomputable def rayClassCharacterPartialSum
    (𝔪 : Modulus K) (χ : RayClassCharacter 𝔪) (x : ℝ) : ℂ :=
  ∑ᶠ I : {I : Ideal (𝓞 K) // 𝔪.IsCoprimeTo I ∧ (Ideal.absNorm I : ℝ) ≤ x},
    (χ (idealClass 𝔪 (I : Ideal (𝓞 K))) : ℂ)

/-- **Exact Chebotarev contract: cancellation of a nontrivial ray class character.** -/
theorem rayClassCharacter_partialSums (𝔪 : Modulus K) (χ : RayClassCharacter 𝔪) (hχ : χ ≠ 1) :
    ∃ δ : ℝ, 0 < δ ∧
      (fun x : ℝ => rayClassCharacterPartialSum 𝔪 χ x) =O[atTop]
        (fun x : ℝ => ((x ^ (1 - δ) : ℝ) : ℂ)) := sorry

/-! ## Layers 4--8: adeles and ideles -/

/-- Additive strong approximation in the finite adeles. -/
theorem denseRange_algebraMap_finiteAdeleRing :
    DenseRange (algebraMap K (IsDedekindDomain.FiniteAdeleRing (𝓞 K) K)) := sorry

abbrev IdeleGroup (K : Type u) [Field K] [NumberField K] := (AdeleRing (𝓞 K) K)ˣ

abbrev IdeleClassGroup (K : Type u) [Field K] [NumberField K] :=
  IdeleGroup K ⧸ (Units.map (algebraMap K (AdeleRing (𝓞 K) K)).toMonoidHom).range

/-- The global idele norm, using squared modulus at complex places. -/
noncomputable def ideleNorm : IdeleGroup K →* Units NNReal := sorry

namespace IdeleClassGroup

/-- The norm-one idele classes; compactness is a theorem of Layer 6. -/
noncomputable def normOne (K : Type u) [Field K] [NumberField K] : Subgroup (IdeleClassGroup K) :=
  sorry

end IdeleClassGroup

/-- Principal units of level `n` in one finite completion. -/
def IsPrincipalUnitOfLevel (v : HeightOneSpectrum (𝓞 K)) (n : ℕ) (x : v.adicCompletion K) : Prop :=
  ∃ y : v.adicCompletionIntegers K, (y : v.adicCompletion K) = x - 1 ∧
    y ∈ (IsLocalRing.maximalIdeal (v.adicCompletionIntegers K)) ^ n

/-- The single idelic congruence subgroup, including the infinite components. -/
noncomputable def IdeleCongruenceSubgroup (𝔪 : Modulus K) : Subgroup (IdeleGroup K) := sorry

noncomputable def RaySubgroup (𝔪 : Modulus K) : Subgroup (IdeleClassGroup K) := sorry

noncomputable def rayClassQuotient (𝔪 : Modulus K) :
    IdeleClassGroup K →* RayClassGroup 𝔪 := sorry

theorem rayClassQuotient_surjective (𝔪 : Modulus K) :
    Function.Surjective (rayClassQuotient 𝔪) := sorry

theorem ker_rayClassQuotient (𝔪 : Modulus K) :
    (rayClassQuotient 𝔪).ker = RaySubgroup 𝔪 := sorry

/-! ## Layer 9: Hecke characters -/

abbrev HeckeCharacter (K : Type u) [Field K] [NumberField K] :=
  ContinuousMonoidHom (IdeleClassGroup K) ℂˣ

noncomputable def HeckeCharacter.ofRayClassCharacter {𝔪 : Modulus K}
    (χ : RayClassCharacter 𝔪) : HeckeCharacter K := sorry

theorem HeckeCharacter.ofRayClassCharacter_apply {𝔪 : Modulus K}
    (χ : RayClassCharacter 𝔪) (y : IdeleClassGroup K) :
    HeckeCharacter.ofRayClassCharacter χ y = χ (rayClassQuotient 𝔪 y) := sorry

noncomputable def RayClassCharacter.induced {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫)
    (η : RayClassCharacter 𝔪) : RayClassCharacter 𝔫 :=
  η.comp (classMap h)

def RayClassCharacter.IsPrimitive {𝔫 : Modulus K} (η : RayClassCharacter 𝔫) : Prop :=
  ∀ (𝔪 : Modulus K) (h : 𝔪 ∣ 𝔫), 𝔪 ≠ 𝔫 →
    ¬ ∃ ψ : RayClassCharacter 𝔪, ψ.induced h = η

theorem RayClassCharacter.not_isPrimitive_one {𝔫 : Modulus K} (h : 𝔫 ≠ Modulus.one K) :
    ¬ (1 : RayClassCharacter 𝔫).IsPrimitive := sorry

noncomputable def HeckeCharacter.shift (χ : HeckeCharacter K) : ℝ := sorry

noncomputable def HeckeCharacter.unitaryPart (χ : HeckeCharacter K) : HeckeCharacter K := sorry

theorem HeckeCharacter.norm_unitaryPart (χ : HeckeCharacter K) (y : IdeleClassGroup K) :
    ‖((χ.unitaryPart y : ℂˣ) : ℂ)‖ = 1 := sorry

theorem HeckeCharacter.shift_eq_zero_iff (χ : HeckeCharacter K) :
    χ.shift = 0 ↔ ∀ y : IdeleClassGroup K, ‖((χ y : ℂˣ) : ℂ)‖ = 1 := sorry

theorem HeckeCharacter.shift_ofRayClassCharacter {𝔪 : Modulus K} (η : RayClassCharacter 𝔪) :
    (HeckeCharacter.ofRayClassCharacter η).shift = 0 := sorry

/-! ## Layer 10: infinity types -/

open scoped Classical in
/-- The modulus `(n)·∞` over `ℚ`, used by the ray-class/Dirichlet-character and
cyclotomic carrier comparisons. Including the real place is essential: omitting it quotients
the finite residue-unit group by the sign of `-1`. -/
noncomputable def ratModulus (n : ℕ)
    (h : (Ideal.span {(n : 𝓞 ℚ)} : Ideal (𝓞 ℚ)) ≠ ⊥) : Modulus ℚ where
  finitePart := Ideal.span {(n : 𝓞 ℚ)}
  finitePart_ne_bot := h
  infinitePart := Finset.univ

/-- The integer exponents of an algebraic infinity type, indexed by embeddings into `ℂ`. -/
structure InfinityType (K : Type u) [Field K] [NumberField K] where
  exponent : (K →+* ℂ) → ℤ

/-! ## Layer 11: orders and Picard groups -/

structure NumberFieldOrder (K : Type u) [Field K] [NumberField K] where
  toSubalgebra : Subalgebra ℤ K
  finite : Module.Finite ℤ toSubalgebra
  spans : Submodule.span ℚ (toSubalgebra : Set K) = ⊤

noncomputable instance (O : NumberFieldOrder K) : IsFractionRing O.toSubalgebra K := sorry

noncomputable def NumberFieldOrder.conductor (O : NumberFieldOrder K) : Ideal (𝓞 K) := sorry

/-- A fractional ideal is proper when its multiplier ring is exactly the given order. This
predicate does not include invertibility. -/
def NumberFieldOrder.IsProperFractionalIdeal (O : NumberFieldOrder K)
    (I : FractionalIdeal (O.toSubalgebra)⁰ K) : Prop := sorry

/-- The group-valued carrier used by `Pic` and `NarrowPic`: invertible fractional ideals.
Every member is proper, but the converse requires an additional hypothesis on the order. -/
abbrev NumberFieldOrder.invertibleProperFractionalIdeals (O : NumberFieldOrder K) :=
  (FractionalIdeal (O.toSubalgebra)⁰ K)ˣ

theorem NumberFieldOrder.invertible_isProper (O : NumberFieldOrder K)
    (I : O.invertibleProperFractionalIdeals) :
    O.IsProperFractionalIdeal (I : FractionalIdeal (O.toSubalgebra)⁰ K) := sorry

/-- Raw proper fractional ideals, including possible noninvertible ideals. This is not a group. -/
def NumberFieldOrder.properFractionalIdeals (O : NumberFieldOrder K) :=
  {I : FractionalIdeal (O.toSubalgebra)⁰ K // O.IsProperFractionalIdeal I}

/-- The explicit hypothesis under which properness and invertibility agree. -/
def NumberFieldOrder.IsGorenstein (O : NumberFieldOrder K) : Prop := sorry

theorem NumberFieldOrder.isProper_iff_isUnit_of_isGorenstein (O : NumberFieldOrder K)
    (hO : O.IsGorenstein) (I : FractionalIdeal (O.toSubalgebra)⁰ K) :
    O.IsProperFractionalIdeal I ↔ IsUnit I := sorry

/-- Cox's proper-ideal equivalence is used only for quadratic orders. -/
theorem NumberFieldOrder.isProper_iff_isUnit_of_finrank_eq_two (O : NumberFieldOrder K)
    (hK : Module.finrank ℚ K = 2) (I : FractionalIdeal (O.toSubalgebra)⁰ K) :
    O.IsProperFractionalIdeal I ↔ IsUnit I := sorry

/-- Homothety classes of all nonzero fractional ideals form a monoid, not in general a group. -/
noncomputable def IdealClassMonoid (O : NumberFieldOrder K) : Type u := sorry

noncomputable instance (O : NumberFieldOrder K) : CommMonoid (IdealClassMonoid O) := sorry

noncomputable def NumberFieldOrder.mkIdealClassMonoid (O : NumberFieldOrder K)
    (I : O.properFractionalIdeals) : IdealClassMonoid O := sorry

noncomputable def Pic (O : NumberFieldOrder K) : Type u := ClassGroup O.toSubalgebra

noncomputable instance (O : NumberFieldOrder K) : CommGroup (Pic O) :=
  inferInstanceAs (CommGroup (ClassGroup O.toSubalgebra))

noncomputable def NumberFieldOrder.mkPic (O : NumberFieldOrder K)
    (I : O.invertibleProperFractionalIdeals) : Pic O := sorry

/-- The units in the ideal class monoid are exactly the invertible ideal classes. -/
noncomputable def picEquivUnitsIdealClassMonoid (O : NumberFieldOrder K) :
    Pic O ≃* (IdealClassMonoid O)ˣ := sorry

theorem NumberFieldOrder.mkPic_surjective (O : NumberFieldOrder K) :
    Function.Surjective O.mkPic := sorry

/-- Principal invertible proper ideals with a totally positive generator. -/
noncomputable def NumberFieldOrder.narrowPrincipal (O : NumberFieldOrder K) :
    Subgroup O.invertibleProperFractionalIdeals := sorry

/-- The narrow quotient uses the same invertible carrier as `Pic`. -/
def NarrowPic (O : NumberFieldOrder K) : Type u :=
  O.invertibleProperFractionalIdeals ⧸ O.narrowPrincipal

noncomputable instance (O : NumberFieldOrder K) : CommGroup (NarrowPic O) :=
  inferInstanceAs (CommGroup (O.invertibleProperFractionalIdeals ⧸ O.narrowPrincipal))

/-- The canonical forget-positivity map from the narrow to the wide Picard group. -/
noncomputable def NumberFieldOrder.narrowToPic (O : NumberFieldOrder K) :
    NarrowPic O →* Pic O := sorry

/-- Evaluation of the forget-positivity map on an invertible proper ideal class. -/
theorem NumberFieldOrder.narrowToPic_mk (O : NumberFieldOrder K)
    (I : O.invertibleProperFractionalIdeals) :
    O.narrowToPic (QuotientGroup.mk I) = O.mkPic I := sorry

theorem NumberFieldOrder.narrowToPic_surjective (O : NumberFieldOrder K) :
    Function.Surjective O.narrowToPic := sorry

/-- Sign vectors at the real places. The quotient by the signs of order units is the
kernel term in the narrow-to-wide exact sequence. -/
abbrev RealSignGroup (K : Type u) [Field K] [NumberField K] :=
  {w : InfinitePlace K // w.IsReal} → Multiplicative (ZMod 2)

noncomputable def NumberFieldOrder.unitSignMap (O : NumberFieldOrder K) :
    O.toSubalgebraˣ →* RealSignGroup K := sorry

def UnitSignQuotient (O : NumberFieldOrder K) : Type u :=
  RealSignGroup K ⧸ O.unitSignMap.range

noncomputable instance (O : NumberFieldOrder K) : CommGroup (UnitSignQuotient O) :=
  inferInstanceAs (CommGroup (RealSignGroup K ⧸ O.unitSignMap.range))

/-- The boundary map in
`Oˣ → {±1}^{r₁} → NarrowPic O → Pic O → 1`. -/
noncomputable def NumberFieldOrder.unitSignBoundary (O : NumberFieldOrder K) :
    UnitSignQuotient O →* NarrowPic O := sorry

theorem NumberFieldOrder.unitSignBoundary_injective (O : NumberFieldOrder K) :
    Function.Injective O.unitSignBoundary := sorry

theorem NumberFieldOrder.ker_narrowToPic (O : NumberFieldOrder K) :
    O.narrowToPic.ker = O.unitSignBoundary.range := sorry

/-- Morphisms of orders, used to state functoriality without hiding the comparison maps. -/
structure NumberFieldOrder.Hom (O O' : NumberFieldOrder K) where
  toAlgHom : O.toSubalgebra →ₐ[ℤ] O'.toSubalgebra

noncomputable def NumberFieldOrder.Hom.mapPic {O O' : NumberFieldOrder K}
    (f : O.Hom O') : Pic O →* Pic O' := sorry

noncomputable def NumberFieldOrder.Hom.mapNarrowPic {O O' : NumberFieldOrder K}
    (f : O.Hom O') : NarrowPic O →* NarrowPic O' := sorry

theorem NumberFieldOrder.narrowToPic_natural {O O' : NumberFieldOrder K}
    (f : O.Hom O') :
    f.mapPic.comp O.narrowToPic = O'.narrowToPic.comp f.mapNarrowPic := sorry

/-! Extension and contraction are group equivalences only after restricting to invertible ideals
prime to the conductor. The restrictions are part of the carrier types, not side conditions erased
from the public API. -/

def NumberFieldOrder.IsPrimeAwayFromConductor (O : NumberFieldOrder K)
    (p : Ideal O.toSubalgebra) : Prop := sorry

def NumberFieldOrder.primesAwayFromConductor (O : NumberFieldOrder K) :=
  {p : Ideal O.toSubalgebra // O.IsPrimeAwayFromConductor p}

def NumberFieldOrder.maximalPrimesAwayFromConductor (O : NumberFieldOrder K) :=
  {p : Ideal (𝓞 K) // p.IsPrime ∧ ¬ O.conductor ≤ p}

/-- Extension and contraction give the prime correspondence only away from the conductor. -/
noncomputable def NumberFieldOrder.primeExtensionContractionEquiv (O : NumberFieldOrder K) :
    O.primesAwayFromConductor ≃ O.maximalPrimesAwayFromConductor := sorry

noncomputable def NumberFieldOrder.invertibleProperIdealsPrimeToConductor
    (O : NumberFieldOrder K) : Subgroup O.invertibleProperFractionalIdeals := sorry

noncomputable def NumberFieldOrder.maximalIdealsPrimeToConductor
    (O : NumberFieldOrder K) : Subgroup (FractionalIdeal (𝓞 K)⁰ K)ˣ := sorry

noncomputable def NumberFieldOrder.extendPrimeToConductor (O : NumberFieldOrder K) :
    O.invertibleProperIdealsPrimeToConductor →*
      O.maximalIdealsPrimeToConductor := sorry

noncomputable def NumberFieldOrder.contractPrimeToConductor (O : NumberFieldOrder K) :
    O.maximalIdealsPrimeToConductor →*
      O.invertibleProperIdealsPrimeToConductor := sorry

theorem NumberFieldOrder.contract_extendPrimeToConductor (O : NumberFieldOrder K) :
    O.contractPrimeToConductor.comp O.extendPrimeToConductor = MonoidHom.id _ := sorry

theorem NumberFieldOrder.extend_contractPrimeToConductor (O : NumberFieldOrder K) :
    O.extendPrimeToConductor.comp O.contractPrimeToConductor = MonoidHom.id _ := sorry

noncomputable def NumberFieldOrder.extensionContractionEquiv (O : NumberFieldOrder K) :
    O.invertibleProperIdealsPrimeToConductor ≃*
      O.maximalIdealsPrimeToConductor := sorry

/-- The maximal order as a `NumberFieldOrder`, making the specialization explicit. -/
noncomputable def maximalNumberFieldOrder
    (K : Type u) [Field K] [NumberField K] : NumberFieldOrder K := sorry

noncomputable def maximalOrderPicEquiv :
    Pic (maximalNumberFieldOrder K) ≃* ClassGroup (𝓞 K) := sorry

abbrev NarrowClassGroup (K : Type u) [Field K] [NumberField K] :=
  NarrowPic (maximalNumberFieldOrder K)

noncomputable def narrowClassToClass :
    NarrowClassGroup K →* ClassGroup (𝓞 K) :=
  (maximalOrderPicEquiv (K := K)).toMonoidHom.comp
    (maximalNumberFieldOrder K).narrowToPic

/-- Compatibility of the order-theoretic map with its maximal-order specialization. -/
theorem narrowClassToClass_eq :
    narrowClassToClass (K := K) =
      (maximalOrderPicEquiv (K := K)).toMonoidHom.comp
        (maximalNumberFieldOrder K).narrowToPic := rfl

/-- Backwards-compatible existential corollary. -/
theorem narrowPic_surjective (O : NumberFieldOrder K) :
    ∃ f : NarrowPic O →* Pic O, Function.Surjective f :=
  ⟨O.narrowToPic, O.narrowToPic_surjective⟩

theorem finite_pic (O : NumberFieldOrder K) : Finite (Pic O) := sorry

theorem finite_narrowPic (O : NumberFieldOrder K) : Finite (NarrowPic O) := sorry

/-- A regression carrier for the cubic example in the normative README. -/
structure NumberFieldOrder.ProperNoninvertibleIdealExample
    (K : Type u) [Field K] [NumberField K] where
  order : NumberFieldOrder K
  ideal : FractionalIdeal (order.toSubalgebra)⁰ K
  proper : order.IsProperFractionalIdeal ideal
  not_invertible : ¬ IsUnit ideal
  not_gorenstein : ¬ order.IsGorenstein

/-- The regression ideal remains a nonunit after passing to the ideal class monoid. -/
theorem NumberFieldOrder.ProperNoninvertibleIdealExample.class_not_isUnit
    (E : NumberFieldOrder.ProperNoninvertibleIdealExample K) :
    ¬ IsUnit (E.order.mkIdealClassMonoid ⟨E.ideal, E.proper⟩) := sorry

/-- The order `ℤ + 2ℤ∛2 + 2ℤ(∛2)²` and ideal
`8ℤ + 2ℤ∛2 + 2ℤ(∛2)²` from the README instantiate this cubic regression. -/
theorem exists_cubic_properNoninvertibleIdealExample :
    ∃ (F : Type u) (_ : Field F) (_ : NumberField F),
      Module.finrank ℚ F = 3 ∧
        Nonempty (NumberFieldOrder.ProperNoninvertibleIdealExample F) := sorry

end TauCetiRoadmap.GlobalNumberFields
